scripts/api-modeling/config/envConfig.js
scripts/api-modeling/package.json
scripts/api-modeling/scripts/front_generate_api.js
scripts/api-modeling/swagger.json

generate api script should support github api after repo migrate github.

[feature] update api generate script for support github

---

.github/workflows/pr-release-2-main.yml

cherry-pick-pr-11

---

src/api/common.d.ts
src/api/common.enum.ts
src/api/workflow/index.d.ts
src/api/workflow/index.enum.ts
src/api/workflow/index.ts
src/components/OrderStatusTag/index.tsx
src/hooks/useStaticStatus/__snapshots__/index.test.tsx.snap
src/hooks/useStaticStatus/index.data.ts
src/hooks/useStaticStatus/index.test.tsx
src/hooks/useStaticStatus/index.tsx
src/locale/en-US/order.ts
src/locale/zh-CN/order.ts
src/page/Home/OrderList/index.test.tsx
src/page/Order/Detail/Modal/OrderHistory/__snapshots__/index.test.tsx.snap
src/page/Order/Detail/Modal/OrderHistory/index.test.tsx
src/page/Order/Detail/Modal/OrderHistory/index.tsx
src/page/Order/Detail/OrderSteps/__snapshots__/index.test.tsx.snap
src/page/Order/Detail/OrderSteps/index.test.tsx
src/page/Order/Detail/OrderSteps/index.tsx
src/page/Order/Detail/OrderSteps/index.type.ts
src/page/Order/Detail/__snapshots__/index.test.tsx.snap
src/page/Order/Detail/__testData__/index.tsx
src/page/Order/Detail/index.test.tsx
src/page/Order/Detail/index.tsx
src/page/Order/Detail/useModifySql.test.tsx
src/page/Order/List/OrderListFilterForm/index.test.tsx
src/page/Order/List/OrderListFilterForm/index.tsx
src/page/Order/List/__snapshots__/index.test.tsx.snap
src/page/Order/List/column.tsx

[issues#157](https://github.com/actiontech/sqle/issues/157) 
[issues#49](https://github.com/actiontech/sqle/issues/49)

[feature]:support  issue#49 and issue#157

---

src/page/Order/Detail/OrderSteps/index.test.tsx
src/page/Order/Detail/OrderSteps/index.tsx

[#177](https://github.com/actiontech/sqle/issues/177)
[#178](https://github.com/actiontech/sqle/issues/178)

[bugfix]:fix issue#178,#177

---

src/page/Order/Detail/index.tsx

[#176](https://github.com/actiontech/sqle/issues/176)

[bugfix]:hidden close button while exec_failed #176

---

src/page/User/Modal/UpdateUser/index.test.tsx
src/page/User/Modal/UserForm/index.tsx

[fix]: remove username rules when update user

---

craco.config.js
src/page/Order/Create/index.test.tsx
src/page/Order/Create/index.tsx
src/page/Order/Detail/__testData__/index.tsx
src/page/Order/Detail/index.test.tsx
src/page/Order/Detail/useModifySql.ts
src/page/Order/hooks/useAllowAuditLevel.test.tsx
src/page/Order/hooks/useAllowAuditLevel.ts

[fix]: missing reset button disabled state

---

src/page/RuleTemplate/RuleTemplateForm/RuleSelect/RuleManagerModal/__snapshots__/index.test.tsx.snap
src/page/RuleTemplate/RuleTemplateForm/RuleSelect/RuleManagerModal/index.less
src/page/RuleTemplate/RuleTemplateForm/RuleSelect/RuleManagerModal/index.tsx

[style]: (RuleManagerModal) set form labl wrap

---

src/locale/zh-CN/audit.ts
src/locale/zh-CN/order.ts
src/page/Order/AuditResult/__snapshots__/index.test.tsx.snap
src/page/Order/AuditResult/index.tsx
src/page/Order/AuditResult/index.type.ts
src/page/Order/Create/__snapshots__/index.test.tsx.snap
src/page/Order/Create/index.tsx
src/page/Order/Detail/Modal/ModifySqlModal/index.test.tsx
src/page/Order/Detail/Modal/ModifySqlModal/index.tsx
src/page/Order/Detail/Modal/ModifySqlModal/index.type.ts
src/page/Order/Detail/__snapshots__/index.test.tsx.snap
src/page/Order/Detail/__testData__/index.tsx
src/page/Order/Detail/index.tsx
src/page/Order/Detail/useModifySql.test.tsx
src/page/Order/Detail/useModifySql.ts
src/page/Order/List/__snapshots__/index.test.tsx.snap
src/page/Order/List/column.tsx
src/page/Order/List/index.test.tsx

[sqle-issue-284](https://github.com/actiontech/sqle/issues/284)

[feature] add task score in task result

---

src/page/UserCenter/Common/__snapshots__/index.test.ts.snap
src/page/UserCenter/Common/generateTag.tsx
src/page/UserCenter/Common/index.test.ts
src/page/UserCenter/Role/RoleList/__snapshots__/index.test.tsx.snap
src/page/UserCenter/Role/RoleList/tableColumn.tsx
src/page/UserCenter/User/UserList/__snapshots__/index.test.tsx.snap
src/page/UserCenter/User/UserList/__testData__/index.ts
src/page/UserCenter/User/UserList/tableHeader.tsx
src/page/UserCenter/UserGroup/UserGroupList/__snapshots__/index.test.tsx.snap
src/page/UserCenter/UserGroup/UserGroupList/tableHeader.tsx

[style]: use tags to display table data

---

src/page/UserCenter/UserGroup/Modal/AddUserGroup/index.test.tsx
src/page/UserCenter/UserGroup/Modal/UpdateUserGroup/__snapshots__/index.test.tsx.snap
src/page/UserCenter/UserGroup/Modal/UpdateUserGroup/index.test.tsx
src/page/UserCenter/UserGroup/Modal/UserGroupForm/UserGroupForm.tsx

[sqle-issue-325](https://github.com/actiontech/sqle/issues/325)

[bugfix]: update user group name validate rule

---

src/page/UserCenter/UserGroup/Modal/AddUserGroup/index.test.tsx
src/page/UserCenter/UserGroup/Modal/AddUserGroup/index.tsx
src/page/UserCenter/UserGroup/Modal/UpdateUserGroup/index.test.tsx
src/page/UserCenter/UserGroup/Modal/UpdateUserGroup/index.tsx

fix [sqle-issue-326](https://github.com/actiontech/sqle/issues/326)

[bugfix]: submit button is always loading after create user group error

---

src/locale/zh-CN/userGroup.ts
src/page/UserCenter/Role/Modal/AddRole/index.test.tsx
src/page/UserCenter/Role/Modal/AddRole/index.tsx
src/page/UserCenter/Role/Modal/UpdateRole/index.test.tsx
src/page/UserCenter/Role/Modal/UpdateRole/index.tsx
src/page/UserCenter/User/Modal/AddUser/index.test.tsx
src/page/UserCenter/User/Modal/AddUser/index.tsx
src/page/UserCenter/User/Modal/UpdateUser/index.test.tsx
src/page/UserCenter/User/Modal/UpdateUser/index.tsx
src/page/UserCenter/UserGroup/Modal/AddUserGroup/index.test.tsx
src/page/UserCenter/UserGroup/Modal/AddUserGroup/index.tsx
src/page/UserCenter/UserGroup/Modal/UpdateUserGroup/index.test.tsx
src/page/UserCenter/UserGroup/Modal/UpdateUserGroup/index.tsx

[sqle-issue-326](https://github.com/actiontech/sqle/issues/326)

[feature]: add create/update success tips for user group

---

src/page/RuleTemplate/RuleTemplateForm/BaseInfoForm/index.tsx
src/page/RuleTemplate/UpdateRuleTemplate/index.test.tsx
src/page/RuleTemplate/__testData__/index.ts

[sqle-issue-361](https://github.com/actiontech/sqle/issues/361)

[bugfix]: user can not update rule template when rule template name include special letter

---

src/page/AuditPlan/PlanForm/AuditTaskType/AuditTaskType.tsx
src/page/AuditPlan/PlanForm/__snapshots__/index.test.tsx.snap
src/page/AuditPlan/PlanForm/index.test.tsx
src/page/AuditPlan/PlanList/__testData__/index.ts
src/page/AuditPlan/UpdatePlan/__snapshots__/index.test.tsx.snap
src/page/AuditPlan/UpdatePlan/index.test.tsx
src/testUtils/customQuery.ts

fix [sqle-issue-366](https://github.com/actiontech/sqle/issues/366)

[feature] fix audit task not set new field value after user update audit task

---

scripts/api-modeling/swagger.json
src/api/common.d.ts
src/api/configuration/index.d.ts
src/api/configuration/index.ts
src/api/global/index.d.ts
src/api/global/index.ts
src/components/Nav/Header/Modal/VersionModal/index.test.tsx
src/components/Nav/Header/Modal/VersionModal/index.tsx
src/data/EmitterKey.ts
src/data/ModalName.ts
src/locale/zh-CN/system.ts
src/page/System/License/Modal/ImportLicense.test.tsx
src/page/System/License/Modal/ImportLicense.tsx
src/page/System/License/Modal/__snapshots__/ImportLicense.test.tsx.snap
src/page/System/License/__snapshots__/index.test.tsx.snap
src/page/System/License/__testData__/index.ts
src/page/System/License/index.test.tsx
src/page/System/License/index.tsx
src/page/System/__snapshots__/index.test.tsx.snap
src/page/System/index.test.tsx
src/page/System/index.tsx
src/page/UserCenter/User/UserList/tableHeader.tsx
src/store/index.ts
src/store/system/index.ts

[sqle-issue-335](https://github.com/actiontech/sqle/issues/335)

[feature]: add license for sqle-ee

---

src/api/configuration/index.ts

[sqle-issue-335](https://github.com/actiontech/sqle/issues/335)

[api] rebuild api

---

src/page/System/License/Modal/ImportLicense.test.tsx
src/page/System/License/Modal/ImportLicense.tsx
src/page/System/License/Modal/__snapshots__/ImportLicense.test.tsx.snap
src/page/System/License/__snapshots__/index.test.tsx.snap
src/page/System/License/index.tsx

[[sqle-issue-335]](https://github.com/actiontech/sqle/issues/335)

[bugfix]: fix import license can not get file from form

---

craco.config.js
src/api/common.d.ts
src/page/DataSource/DataSourceForm/DatabaseFormItem/index.test.tsx
src/page/DataSource/DataSourceForm/DatabaseFormItem/index.tsx
src/page/DataSource/DataSourceForm/index.tsx
src/page/DataSource/UpdateDataSource/__snapshots__/index.test.tsx.snap

[sqle-issue-268](https://github.com/actiontech/sqle/issues/268)

[feature] update datasource connect request params

---

src/page/AuditPlan/PlanDetail/Detail/Record/__snapshots__/index.test.tsx.snap
src/page/AuditPlan/PlanDetail/Detail/Record/index.tsx
src/page/AuditPlan/PlanDetail/__testData__/index.ts
src/styles/_variable.less
src/styles/tool.less

[sqle-issue-382](https://github.com/actiontech/sqle/issues/382)

[feature] update audit task report icon and empty value

---

src/locale/zh-CN/order.ts
src/page/Order/Detail/OrderSteps/__snapshots__/index.test.tsx.snap
src/page/Order/Detail/OrderSteps/index.test.tsx
src/page/Order/Detail/OrderSteps/index.tsx
src/page/Order/Detail/index.tsx

https://github.com/actiontech/sqle/issues/394

[bugfix] disable sql execute button when current time is out of maintenance time

---

src/page/AuditPlan/CreatePlan/__snapshots__/index.test.tsx.snap
src/page/AuditPlan/PlanForm/DataSource/DataSource.tsx
src/page/AuditPlan/PlanForm/__snapshots__/index.test.tsx.snap
src/page/AuditPlan/UpdatePlan/__snapshots__/index.test.tsx.snap
src/page/DataSource/AddDataSource/__snapshots__/index.test.tsx.snap
src/page/DataSource/DataSourceForm/DatabaseFormItem/index.tsx
src/page/DataSource/DataSourceForm/index.tsx
src/page/DataSource/UpdateDataSource/__snapshots__/index.test.tsx.snap
src/page/Order/List/OrderListFilterForm/index.tsx
src/page/Order/List/__snapshots__/index.test.tsx.snap
src/page/Rule/__snapshots__/index.test.tsx.snap
src/page/Rule/index.tsx
src/page/UserCenter/UserGroup/Modal/UserGroupForm/UserGroupForm.tsx
src/page/WorkflowTemplate/WorkflowTemplateForm/BaseForm/index.tsx
src/page/WorkflowTemplate/WorkflowTemplateForm/ProgressConfig/index.tsx

fix https://github.com/actiontech/sqle/issues/404

[feature] add search feature in some select component

---

src/page/AuditPlan/PlanDetail/Detail/Record/__snapshots__/index.test.tsx.snap
src/page/AuditPlan/PlanDetail/Detail/Record/index.tsx

https://github.com/actiontech/sqle/issues/382

[feature] update audit plan success icon

---

src/locale/zh-CN/audit.ts

https://github.com/actiontech/sqle/issues/367

[feature] update table title desc for rollback of audit result table

---

src/locale/zh-CN/order.ts
src/page/Order/AuditResult/__snapshots__/index.test.tsx.snap
src/page/Order/AuditResult/index.test.tsx
src/page/Order/AuditResult/index.tsx
src/page/Order/AuditResult/index.type.ts
src/page/Order/Create/__snapshots__/index.test.tsx.snap
src/page/Order/Create/index.test.tsx
src/page/Order/Create/index.tsx
src/page/Order/Detail/__snapshots__/index.test.tsx.snap
src/page/Order/Detail/index.test.tsx
src/page/Order/Detail/index.tsx

https://github.com/actiontech/sqle/issues/331

[feature] user can't update/create order by empty sql

---

src/api/common.d.ts
src/api/common.enum.ts
src/api/configuration/index.d.ts
src/api/configuration/index.ts
src/hooks/useStaticStatus/index.data.ts
src/locale/zh-CN/ruleTemplate.ts
src/locale/zh-CN/system.ts
src/page/System/SMTPSetting/__snapshots__/index.test.tsx.snap
src/page/System/SMTPSetting/index.test.tsx
src/page/System/SMTPSetting/index.tsx
src/page/System/Wechat/Wechat.tsx

https://github.com/actiontech/sqle/issues/407

[feature] user can switch email notice in system config page now.

---

src/locale/zh-CN/common.ts
src/page/DataSource/DataSourceForm/MaintenanceTimePicker/MaintenanceTimePicker.test.tsx
src/page/DataSource/DataSourceForm/MaintenanceTimePicker/MaintenanceTimePicker.tsx
src/page/DataSource/DataSourceForm/MaintenanceTimePicker/__snapshots__/MaintenanceTimePicker.test.tsx.snap

fix https://github.com/actiontech/sqle/issues/428

[bugfix]: time range picker will remove all time which are after use delete

---

src/page/System/Wechat/Wechat.test.tsx
src/page/System/Wechat/Wechat.tsx
src/page/System/Wechat/__snapshots__/Wechat.test.tsx.snap

fix https://github.com/actiontech/sqle/issues/430

[bugfix]: the agent id of wechat must be number

---

src/api/audit_plan/index.d.ts
src/api/audit_plan/index.ts
src/api/common.d.ts
src/locale/zh-CN/auditPlan.ts
src/page/AuditPlan/PlanDetail/Detail/Report/__snapshots__/index.test.tsx.snap
src/page/AuditPlan/PlanDetail/Detail/Report/index.test.tsx
src/page/AuditPlan/PlanDetail/Detail/Report/index.tsx

https://github.com/actiontech/sqle/issues/429

update audit task report title

---

src/api/common.d.ts
src/api/instance/index.d.ts
src/api/instance/index.enum.ts
src/locale/zh-CN/workflowTemplate.ts
src/page/WorkflowTemplate/CreateWorkflowTemplate/__snapshots__/index.test.tsx.snap
src/page/WorkflowTemplate/UpdateWorkflowTemplate/__snapshots__/index.test.tsx.snap
src/page/WorkflowTemplate/UpdateWorkflowTemplate/index.test.tsx
src/page/WorkflowTemplate/UpdateWorkflowTemplate/index.tsx
src/page/WorkflowTemplate/WorkflowTemplateForm/ProgressConfig/__snapshots__/index.test.tsx.snap
src/page/WorkflowTemplate/WorkflowTemplateForm/ProgressConfig/index.test.tsx
src/page/WorkflowTemplate/WorkflowTemplateForm/ProgressConfig/index.tsx
src/page/WorkflowTemplate/WorkflowTemplateForm/ProgressConfig/index.type.ts
src/page/WorkflowTemplate/WorkflowTemplateForm/__snapshots__/index.test.tsx.snap
src/page/WorkflowTemplate/__testData__/index.ts

https://github.com/actiontech/sqle/issues/453

Issue/453: add review user type in workflow progress config page.

---

src/page/AuditPlan/PlanForm/DataSource/DataSource.tsx
src/page/AuditPlan/PlanForm/index.test.tsx
src/page/AuditPlan/UpdatePlan/index.test.tsx

https://github.com/actiontech/sqle/issues/453

[feature] update get datasource request params in create audit task page

---

src/api/audit_plan/index.d.ts
src/api/audit_plan/index.ts
src/api/common.d.ts
src/api/common.enum.ts
src/components/IconTipsLabel/IconTipsLabel.test.tsx
src/components/IconTipsLabel/IconTipsLabel.tsx
src/components/IconTipsLabel/__snapshots__/IconTipsLabel.test.tsx.snap
src/components/IconTipsLabel/index.ts
src/data/ModalName.ts
src/data/common.ts
src/locale/zh-CN/auditPlan.ts
src/page/AuditPlan/PlanList/Modal/SubscribeNotice/WebhooksTemplateHelp.tsx
src/page/AuditPlan/PlanList/Modal/SubscribeNotice/index.data.tsx
src/page/AuditPlan/PlanList/Modal/SubscribeNotice/index.tsx
src/page/AuditPlan/PlanList/Modal/SubscribeNotice/index.type.ts
src/page/AuditPlan/PlanList/Modal/SubscribeNotice/tests/SubscribeNotice.test.tsx
src/page/AuditPlan/PlanList/Modal/SubscribeNotice/tests/__snapshots__/SubscribeNotice.test.tsx.snap
src/page/AuditPlan/PlanList/Modal/SubscribeNotice/tests/__testData__/index.ts
src/page/AuditPlan/PlanList/Modal/index.tsx
src/page/AuditPlan/PlanList/__snapshots__/index.test.tsx.snap
src/page/AuditPlan/PlanList/index.test.tsx
src/page/AuditPlan/PlanList/index.tsx
src/page/AuditPlan/PlanList/tableColumn.tsx
src/store/auditPlan/index.test.ts
src/store/auditPlan/index.tsx
src/store/index.ts
src/styles/_variable.less
src/styles/tool.less

https://github.com/actiontech/sqle/issues/448

[feature] support subscribe audit task failed message

---

src/components/CronInput/__snapshots__/index.test.tsx.snap
src/components/CronInput/index.data.ts
src/components/CronInput/index.less
src/components/CronInput/index.test.tsx
src/components/CronInput/index.tsx
src/components/CronInput/index.type.ts
src/locale/zh-CN/common.ts
src/page/AuditPlan/CreatePlan/__snapshots__/index.test.tsx.snap
src/page/AuditPlan/PlanForm/__snapshots__/index.test.tsx.snap
src/page/AuditPlan/UpdatePlan/__snapshots__/index.test.tsx.snap

fix https://github.com/actiontech/sqle/issues/471

[feature] optimize cron input

---

scripts/api-modeling/src/core/index.ts
src/App.test.tsx
src/api/common.d.ts
src/api/configuration/index.d.ts
src/api/configuration/index.ts
src/api/oauth2/index.d.ts
src/api/oauth2/index.ts
src/locale/zh-CN/login.ts
src/locale/zh-CN/system.ts
src/page/BindUser/__snapshots__/index.test.tsx.snap
src/page/BindUser/index.test.tsx
src/page/BindUser/index.tsx
src/page/BindUser/index.type.ts
src/page/Login/__snapshots__/index.test.tsx.snap
src/page/Login/index.test.tsx
src/page/Login/index.tsx
src/page/System/Oauth/Oauth.tsx
src/page/System/Oauth/Quath.test.tsx
src/page/System/Oauth/__snapshots__/Quath.test.tsx.snap
src/page/System/Oauth/__testData__/index.ts
src/page/System/Oauth/index.type.ts
src/page/System/__snapshots__/index.test.tsx.snap
src/page/System/index.tsx
src/router/config.tsx
src/styles/tool.less
src/testUtils/customRender.tsx

https://github.com/actiontech/sqle/issues/470

[feature] support oauth2.0 

---

src/locale/zh-CN/login.ts
src/page/Login/__snapshots__/index.test.tsx.snap
src/page/Login/index.tsx

https://github.com/actiontech/sqle/issues/470

[feature] update oauth login button location.

---

.github/workflows/main.yml
src/locale/zh-CN/system.ts

https://github.com/actiontech/sqle/issues/470

[feature] update text for oauth config

---

src/api/common.d.ts
src/locale/zh-CN/login.ts
src/page/BindUser/index.test.tsx
src/page/BindUser/index.tsx

https://github.com/actiontech/sqle/issues/470

[feature] update url param name of bind user page.

---

src/api/common.d.ts
src/api/instance/index.enum.ts
src/api/sql_query/index.d.ts
src/api/sql_query/index.ts
src/locale/zh-CN/system.ts
src/page/System/LDAPSetting/__snapshots__/index.test.tsx.snap
src/page/System/LDAPSetting/index.test.tsx
src/page/System/LDAPSetting/index.tsx
src/page/System/LDAPSetting/index.type.ts

[Issue/250](https://github.com/actiontech/sqle/issues/250)

suppot ldaps

---

src/locale/zh-CN/order.ts
src/page/Order/Detail/__snapshots__/index.test.tsx.snap
src/page/Order/Detail/index.tsx

fix https://github.com/actiontech/sqle/issues/517

[feature] show datasource and schema in order detail page

---

src/page/Order/List/__snapshots__/index.test.tsx.snap
src/page/Order/List/column.tsx

fix https://github.com/actiontech/sqle/issues/516

[bugfix] fix order desc style

---

src/api/common.d.ts
src/api/common.enum.ts
src/locale/zh-CN/dataSource.ts
src/page/DataSource/AddDataSource/__snapshots__/index.test.tsx.snap
src/page/DataSource/AddDataSource/index.test.tsx
src/page/DataSource/AddDataSource/index.tsx
src/page/DataSource/DataSourceForm/index.tsx
src/page/DataSource/DataSourceForm/index.type.ts
src/page/DataSource/UpdateDataSource/__snapshots__/index.test.tsx.snap
src/page/DataSource/UpdateDataSource/index.test.tsx
src/page/DataSource/UpdateDataSource/index.tsx

https://github.com/actiontech/sqle/issues/541

[feature]: update DataSourceForm

---

src/page/Order/Create/__snapshots__/index.test.tsx.snap
src/page/Order/Create/index.test.tsx
src/page/Order/Create/index.tsx

[fix]: limit the max input length of the order desc to 50

---

src/page/SqlQuery/SqlInput/index.tsx

[fix]: added missing interface param

---

src/page/Order/List/column.tsx

https://github.com/actiontech/sqle/issues/516

[bugfix]: add tool tips for order desc

---

src/page/RuleTemplate/RuleTemplateForm/RuleSelect/RuleManagerModal/__snapshots__/index.test.tsx.snap
src/page/RuleTemplate/RuleTemplateForm/RuleSelect/RuleManagerModal/index.tsx

fix https://github.com/actiontech/sqle/issues/557

[bugfix] update modify rule modal to support show long label

---

src/page/AuditPlan/PlanDetail/Detail/Record/index.tsx
src/page/Login/index.less
src/page/Order/AuditResult/__snapshots__/index.test.tsx.snap
src/page/Order/AuditResult/index.test.tsx
src/page/Order/AuditResult/index.tsx
src/page/Order/List/column.tsx
src/utils/Math.ts
src/utils/test/math.test.ts

fix https://github.com/actiontech/sqle/issues/633

[fix] pass rage only display 2 decimal places.

---

src/components/Nav/__snapshots__/index.test.tsx.snap
src/components/Nav/index.tsx
src/locale/zh-CN/common.ts

fix https://github.com/actiontech/sqle-ee/issues/297

[feature] update page title in ee  version

---

src/api/common.d.ts
src/api/common.enum.ts
src/api/sql_audit/index.d.ts
src/api/sql_audit/index.ts
src/api/workflow/index.d.ts
src/locale/zh-CN/dataSource.ts
src/page/DataSource/DataSourceList/__snapshots__/index.test.tsx.snap
src/page/DataSource/DataSourceList/columns.tsx
src/page/DataSource/__testData__/index.tsx

fix https://github.com/actiontech/sqle/issues/625

[feature] add db type in data source table

---

src/locale/zh-CN/ruleTemplate.ts
src/page/RuleTemplate/RuleTemplateList/__snapshots__/index.test.tsx.snap
src/page/RuleTemplate/RuleTemplateList/column.tsx
src/page/RuleTemplate/RuleTemplateList/index.tsx

fix https://github.com/actiontech/sqle/issues/626

[feature] refactor rule template list card from list to table

---

src/locale/en-US/auditPlan.ts
src/locale/zh-CN/auditPlan.ts

fix https://github.com/actiontech/sqle/issues/707

[bugfix] fix error text

---

src/locale/zh-CN/dashboard.ts
src/page/Home/CommonTable/Table.tsx
src/page/Home/CommonTable/__snapshots__/index.test.tsx.snap
src/page/Home/CommonTable/column.tsx
src/page/Home/DBAPanel/__snapshots__/index.test.tsx.snap
src/page/Home/DBAPanel/index.test.tsx
src/page/Home/DBAPanel/index.tsx
src/page/Home/DEVPanel/__snapshots__/index.test.tsx.snap
src/page/Home/DEVPanel/index.test.tsx
src/page/Home/DEVPanel/index.tsx
src/page/Home/QuickLink/__snapshots__/index.test.tsx.snap
src/page/Home/QuickLink/index.less
src/page/Home/QuickLink/index.test.tsx
src/page/Home/QuickLink/index.tsx
src/page/Home/QuickLink/index.type.ts
src/page/Home/RecentlyOrderPanel/__snapshots__/index.test.tsx.snap
src/page/Home/RecentlyOrderPanel/column.tsx
src/page/Home/RecentlyOrderPanel/index.test.tsx
src/page/Home/RecentlyOrderPanel/index.tsx
src/page/Home/__snapshots__/index.test.tsx.snap
src/page/Home/index.less
src/page/Home/index.tsx

fix: actiontech/sqle/issues/693

[fix]: update dashboard style

---

src/components/CronInput/index.tsx
src/hooks/useCron/index.tsx
src/page/AuditPlan/CreatePlan/__snapshots__/index.test.tsx.snap
src/page/AuditPlan/CreatePlan/index.test.tsx
src/page/AuditPlan/PlanForm/__snapshots__/index.test.tsx.snap
src/page/AuditPlan/PlanForm/index.test.tsx
src/page/AuditPlan/PlanForm/index.tsx

fix https://github.com/actiontech/sqle/issues/712

[feature] update the default value of cron in create audit plan form

---

src/page/Order/Create/SqlInfoForm/index.tsx
src/page/Order/Create/SqlInfoForm/index.type.ts
src/page/Order/Create/__snapshots__/index.test.tsx.snap
src/page/Order/Create/index.test.tsx
src/page/Order/Create/index.tsx

fix https://github.com/actiontech/sqle/issues/698

[feature] generate order name after user select a data source when user don't input order name

---

package.json
yarn.lock

[fix]: ci error

---

src/api/common.d.ts
src/locale/en-US/auditPlan.ts
src/locale/zh-CN/auditPlan.ts
src/page/AuditPlan/CreatePlan/__snapshots__/index.test.tsx.snap
src/page/AuditPlan/CreatePlan/index.test.tsx
src/page/AuditPlan/CreatePlan/index.tsx
src/page/AuditPlan/PlanForm/__snapshots__/index.test.tsx.snap
src/page/AuditPlan/PlanForm/index.test.tsx
src/page/AuditPlan/PlanForm/index.tsx
src/page/AuditPlan/PlanForm/index.type.ts
src/page/AuditPlan/PlanList/__snapshots__/index.test.tsx.snap
src/page/AuditPlan/PlanList/__testData__/index.ts
src/page/AuditPlan/PlanList/index.test.tsx
src/page/AuditPlan/PlanList/tableColumn.tsx
src/page/AuditPlan/UpdatePlan/__snapshots__/index.test.tsx.snap
src/page/AuditPlan/UpdatePlan/index.test.tsx
src/page/AuditPlan/UpdatePlan/index.tsx
src/store/auditPlan/index.test.ts

[feat]: issue-755

---

src/page/Order/List/__snapshots__/index.test.tsx.snap
src/page/Order/List/column.tsx
src/page/Order/List/index.test.tsx

[fix]: formatting assignee column with tag

---

src/App.test.tsx
src/components/Nav/SiderMenu/__snapshots__/index.test.tsx.snap
src/components/Nav/__snapshots__/index.test.tsx.snap
src/router/config.tsx

[fix]: hide report statistics page when role is not admin

---

src/page/AuditPlan/PlanList/__snapshots__/index.test.tsx.snap
src/page/AuditPlan/PlanList/tableColumn.tsx

[feat]: modify auditPlanName column format as a link

---

src/page/SqlQueryEE/index.test.tsx
src/page/SqlQueryEE/index.tsx

https://github.com/actiontech/sqle-ee/issues/459

[feature] update open method of sql query page

---

src/page/Order/AuditResult/AuditResultCollection.tsx
src/page/Order/AuditResult/index.type.ts
src/page/Order/Detail/Modal/OrderHistory/__snapshots__/index.test.tsx.snap
src/page/Order/Detail/OrderSteps/index.tsx
src/page/Order/Detail/OrderSteps/index.type.ts
src/page/Order/Detail/__snapshots__/index.test.tsx.snap
src/page/Order/Detail/index.tsx

[bugfix]: check time in maintenance time

---

src/page/SqlQuery/__snapshots__/index.test.tsx.snap
src/page/SqlQuery/index.tsx

fix https://github.com/actiontech/sqle/issues/904

[bugfix] fix doc link of sql query not work

---

src/page/Order/Create/SqlInfoForm/index.tsx

[fix]: remove empty connect error message

---

src/page/Order/Create/SqlInfoForm/DatabaseInfo.tsx

[fix]: disabled switch sql mode with instance type list

---

src/locale/zh-CN/system.ts
src/page/Home/QuickLink/__snapshots__/index.test.tsx.snap
src/page/Home/QuickLink/index.less
src/page/Home/QuickLink/index.test.tsx
src/page/Home/QuickLink/index.tsx
src/page/Home/__snapshots__/index.test.tsx.snap
src/page/Home/index.test.tsx
src/page/Home/index.tsx
src/styles/_variable.less

fix https://github.com/actiontech/sqle-ee/issues/460

update project name.

---

src/page/UserCenter/User/Modal/UpdateUser/index.test.tsx
src/page/UserCenter/User/Modal/UpdateUser/index.tsx

fix https://github.com/actiontech/sqle/issues/880

[fix]: fix admin can't clear user email

---

src/locale/zh-CN/sqlQuery.ts
src/page/SqlQuery/index.test.tsx
src/page/SqlQuery/index.tsx

fix https://github.com/actiontech/sqle/issues/925

[feature] update the method of open sql query page

---

src/api/audit_plan/index.d.ts
src/api/audit_plan/index.ts
src/api/common.d.ts
src/api/statistic/index.d.ts
src/api/statistic/index.ts
src/hooks/useAuditPlanTypes/__snapshots__/index.test.tsx.snap
src/hooks/useAuditPlanTypes/index.test.tsx
src/hooks/useAuditPlanTypes/index.tsx
src/page/AuditPlan/PlanList/PlanListFilterForm/__snapshots__/index.test.tsx.snap
src/page/AuditPlan/PlanList/PlanListFilterForm/index.test.tsx
src/page/AuditPlan/PlanList/PlanListFilterForm/index.tsx
src/page/AuditPlan/PlanList/PlanListFilterForm/index.type.ts
src/page/AuditPlan/PlanList/__snapshots__/index.test.tsx.snap
src/page/AuditPlan/PlanList/index.test.tsx
src/page/AuditPlan/PlanList/index.tsx
src/testUtils/customQuery.ts
src/testUtils/mockRequest.ts

fix https://github.com/actiontech/sqle/issues/923

[feature] support set filter info for audit plan table.

---

src/App.test.tsx
src/components/Nav/SiderMenu/__snapshots__/index.test.tsx.snap
src/components/Nav/SiderMenu/index.test.tsx
src/components/Nav/SiderMenu/index.tsx
src/components/Nav/__snapshots__/index.test.tsx.snap
src/components/Nav/index.test.tsx
src/page/AuditPlan/PlanList/PlanListFilterForm/__snapshots__/index.test.tsx.snap
src/page/AuditPlan/PlanList/PlanListFilterForm/index.test.tsx
src/page/AuditPlan/PlanList/PlanListFilterForm/index.tsx
src/page/AuditPlan/PlanList/index.test.tsx
src/page/AuditPlan/PlanList/index.tsx
src/router/config.tsx
src/testUtils/mockRedux.tsx
src/types/router.type.ts

fix https://github.com/actiontech/sqle/issues/825

[feature] add router for every audit task type.

---

src/page/System/SMTPSetting/index.test.tsx
src/page/System/SMTPSetting/index.tsx

[bugfix]: issue-807

---

src/page/AuditPlan/PlanList/PlanListFilterForm/__snapshots__/index.test.tsx.snap
src/page/AuditPlan/PlanList/PlanListFilterForm/index.test.tsx
src/page/AuditPlan/PlanList/PlanListFilterForm/index.tsx
src/page/AuditPlan/PlanList/PlanListFilterForm/index.type.ts
src/page/AuditPlan/PlanList/__snapshots__/index.test.tsx.snap
src/page/AuditPlan/PlanList/index.test.tsx

[bugfix]: update the name field of the planlist filter form

---

src/page/Order/Create/SqlInfoForm/__test__/__snapshots__/index.test.tsx.snap
src/page/Order/Create/SqlInfoForm/index.tsx
src/page/Order/Create/__snapshots__/index.test.tsx.snap

fix: https://github.com/actiontech/sqle/issues/1037

[bugfix]: fix problem that cannot create a order in ce mode

---

craco.config.js
src/api/common.d.ts
src/api/instance/index.d.ts
src/api/instance/index.ts
src/api/project/index.d.ts
src/api/project/index.ts
src/api/rule_template/index.d.ts
src/api/rule_template/index.ts
src/api/user/index.d.ts
src/api/user/index.ts
src/api/user_group/index.d.ts
src/api/user_group/index.ts
src/hooks/useProject/__snapshots__/index.test.tsx.snap
src/hooks/useProject/index.test.tsx
src/hooks/useProject/index.tsx
src/hooks/useUsername/index.tsx
src/locale/zh-CN/rule.ts
src/page/ProjectManage/Modal/UpdateProject.tsx
src/page/ProjectManage/Modal/__test__/UpdateProject.test.tsx
src/page/ProjectManage/ProjectList/column.tsx
src/page/ProjectManage/ProjectList/index.test.tsx
src/page/ProjectManage/ProjectList/index.tsx
src/page/Rule/__snapshots__/index.test.tsx.snap
src/page/Rule/index.test.tsx
src/page/Rule/index.tsx
src/testUtils/mockRequest.ts

[feature]:build api and change projectId to projectName while updating the global Rule page

---

src/api/rule_template/index.d.ts
src/api/rule_template/index.ts
src/page/RuleTemplate/RuleTemplateList/Modal/CloneRuleTemplate/index.test.tsx
src/page/RuleTemplate/RuleTemplateList/Modal/CloneRuleTemplate/index.tsx
src/page/RuleTemplate/RuleTemplateList/__snapshots__/index.test.tsx.snap
src/page/RuleTemplate/RuleTemplateList/column.tsx
src/page/RuleTemplate/RuleTemplateList/index.test.tsx
src/page/RuleTemplate/RuleTemplateList/index.tsx
src/page/RuleTemplate/UpdateRuleTemplate/index.test.tsx
src/page/RuleTemplate/UpdateRuleTemplate/index.tsx
src/page/UserCenter/Role/RoleList/RoleListFilterForm/__snapshots__/index.test.tsx.snap
src/page/UserCenter/Role/RoleList/RoleListFilterForm/index.tsx
src/page/UserCenter/Role/RoleList/__snapshots__/index.test.tsx.snap
src/page/UserCenter/User/UserList/UserListFilterForm/__snapshots__/index.test.tsx.snap
src/page/UserCenter/User/UserList/UserListFilterForm/index.tsx
src/page/UserCenter/User/UserList/__snapshots__/index.test.tsx.snap

[feature]:change ruleTemplateId to ruleTemplateName while modify the UserCenter style

---

craco.config.js
src/api/common.d.ts
src/components/RuleList/__snapshots__/index.test.tsx.snap
src/components/RuleList/index.test.tsx
src/components/RuleList/index.tsx
src/locale/zh-CN/ruleTemplate.ts
src/page/GlobalRuleTemplate/CreateRuleTemplate/__snapshots__/index.test.tsx.snap
src/page/GlobalRuleTemplate/RuleTemplateForm/RuleSelect/RuleManagerModal/__snapshots__/index.test.tsx.snap
src/page/GlobalRuleTemplate/RuleTemplateForm/RuleSelect/RuleManagerModal/__testData__/index.ts
src/page/GlobalRuleTemplate/RuleTemplateForm/RuleSelect/RuleManagerModal/index.test.tsx
src/page/GlobalRuleTemplate/RuleTemplateForm/RuleSelect/RuleManagerModal/index.tsx
src/page/GlobalRuleTemplate/RuleTemplateForm/RuleSelect/RuleManagerModal/index.type.ts
src/page/GlobalRuleTemplate/RuleTemplateForm/RuleSelect/__snapshots__/index.test.tsx.snap
src/page/GlobalRuleTemplate/RuleTemplateForm/__snapshots__/index.test.tsx.snap
src/page/GlobalRuleTemplate/UpdateRuleTemplate/__snapshots__/index.test.tsx.snap
src/page/Rule/__testData__/index.ts
src/page/RuleTemplate/RuleTemplateForm/RuleSelect/RuleManagerModal/__snapshots__/index.test.tsx.snap
src/page/RuleTemplate/RuleTemplateForm/RuleSelect/RuleManagerModal/__testData__/index.ts
src/page/RuleTemplate/RuleTemplateForm/RuleSelect/RuleManagerModal/index.test.tsx
src/page/RuleTemplate/RuleTemplateForm/RuleSelect/RuleManagerModal/index.tsx
src/page/RuleTemplate/RuleTemplateForm/RuleSelect/RuleManagerModal/index.type.ts
src/page/RuleTemplate/RuleTemplateForm/RuleSelect/__snapshots__/index.test.tsx.snap

[feature]: add rule annotation and rewrite the edit rule form using BackendForm

---

src/locale/zh-CN/member.ts
src/page/Member/Common/RoleSelector.tsx
src/page/Member/Modal/__test__/__snapshots__/UpdateMember.test.tsx.snap
src/page/Member/Modal/__test__/__snapshots__/UpdateMemberGroup.test.tsx.snap

Fix: actiontech/sqle#1134  actiontech/sqle#1136

[ui]: adjusting project member form styles and table role column descriptions

---

src/locale/en-US/projectManage.ts
src/locale/zh-CN/projectManage.ts
src/page/ProjectManage/ProjectOverview/ProjectInfoBox.tsx
src/page/ProjectManage/ProjectOverview/__test__/__snapshots__/ProjectInfoBox.test.tsx.snap
src/page/ProjectManage/ProjectOverview/__test__/__snapshots__/index.test.tsx.snap
src/page/ProjectManage/ProjectOverview/index.tsx

[ui]: adjust Project Overview Page style and the wrong text

---

src/locale/zh-CN/ruleTemplate.ts

[ui]:(RuleTemplate) adjust text info

---

src/page/Order/AuditResult/AuditResultCollection.tsx
src/page/Order/AuditResult/ScheduleTimeModal.tsx
src/page/Order/AuditResult/__test__/AuditResultCollection.test.tsx
src/page/Order/AuditResult/__test__/ScheduleTimeModal.test.tsx
src/page/Order/Create/SqlInfoForm/DatabaseInfo.tsx
src/page/Order/Create/SqlInfoForm/__test__/DatabaseInfo.test.tsx
src/page/Order/Create/SqlInfoForm/__test__/__snapshots__/DatabaseInfo.test.tsx.snap
src/page/Order/Create/SqlInfoForm/__test__/__snapshots__/index.test.tsx.snap
src/page/Order/Create/SqlInfoForm/__test__/index.test.tsx
src/page/Order/Create/SqlInfoForm/index.tsx
src/page/Order/Create/SqlInfoForm/index.type.ts
src/page/Order/Create/__snapshots__/index.test.tsx.snap
src/page/Order/Create/index.test.tsx
src/page/Order/Create/index.tsx
src/page/Order/Detail/OrderSteps/__test__/index.test.tsx
src/page/Order/Detail/__snapshots__/index.test.tsx.snap
src/page/Order/Detail/__testData__/index.tsx
src/page/Order/Detail/hooks/__test__/useGenerateOrderStepsProps.test.ts
src/page/Order/Detail/hooks/__test__/useInitDataWithRequest.test.ts
src/page/Order/Detail/hooks/__test__/useModifySql.test.tsx
src/page/Order/Detail/index.test.tsx
src/page/Order/List/OrderListFilterForm/index.test.tsx
src/page/Order/List/OrderListFilterForm/index.tsx
src/page/Order/List/OrderListFilterForm/index.type.ts
src/page/Order/List/__snapshots__/index.test.tsx.snap
src/page/Order/List/index.test.tsx
src/page/Order/List/index.tsx
src/page/Order/hooks/__test__/test.data.ts
src/page/Order/hooks/__test__/useAllowAuditLevel.test.tsx
src/page/Order/hooks/__test__/useAuditOrder.test.ts

fix: actiontech/sqle#1157
fix: actiontech/sqle#1156

[bugfix]: adjust the data source form for creating the order, add the click jump event for the order overview table row, and complete the unit test

---

src/App.test.tsx
src/App.tsx
src/data/common.ts
src/hooks/useCurrentUser/index.test.ts
src/hooks/useCurrentUser/index.ts
src/locale/zh-CN/projectManage.ts
src/page/ProjectManage/ProjectList/column.tsx
src/page/ProjectManage/ProjectList/index.test.tsx
src/page/ProjectManage/ProjectList/index.tsx
src/page/RuleTemplate/RuleTemplateList/index.test.tsx
src/store/user/index.test.ts
src/store/user/index.ts

fix: actiontech/sqle#1163
fix: actiontech/sqle#1167

[bugfix]:(ProjectManage) add button action permissions and fix faulty text

---

src/locale/zh-CN/dataSource.ts

[chore]: fixing faulty text

---

src/page/DataSource/AddDataSource/index.test.tsx
src/page/DataSource/AddDataSource/index.tsx
src/page/DataSource/UpdateDataSource/__snapshots__/index.test.tsx.snap
src/page/DataSource/UpdateDataSource/index.test.tsx
src/page/DataSource/UpdateDataSource/index.tsx

[bugfix]: the undefined was passed by the rule template that was not selected while fixing the update data source

---

src/api/common.d.ts
src/api/common.enum.ts
src/api/user/index.d.ts
src/api/user/index.ts
src/hooks/useMember/__snapshots__/index.test.tsx.snap
src/hooks/useMember/index.test.tsx
src/hooks/useMember/index.tsx
src/page/Member/MemberList/FilterForm.tsx
src/page/Member/MemberList/__test__/FilterForm.test.tsx
src/page/Member/MemberList/__test__/index.test.tsx
src/testUtils/mockRequest.ts

[bugfix]: update username source for filtered member list

---

src/hooks/useMonacoEditor/index.test.tsx
src/hooks/useMonacoEditor/index.tsx

[ui]:(MonacoEditor) automatically adapt to browser‘s width

---

src/api/common.d.ts
src/api/configuration/index.d.ts
src/api/configuration/index.ts
src/api/rule_template/index.d.ts
src/api/rule_template/index.ts
src/locale/zh-CN/workflowTemplate.ts
src/page/WorkflowTemplate/UpdateWorkflowTemplate/__snapshots__/index.test.tsx.snap
src/page/WorkflowTemplate/WorkflowTemplateForm/ProgressConfig/__snapshots__/index.test.tsx.snap
src/page/WorkflowTemplate/WorkflowTemplateForm/ProgressConfig/index.test.tsx
src/page/WorkflowTemplate/WorkflowTemplateForm/ProgressConfig/index.tsx
src/page/WorkflowTemplate/WorkflowTemplateForm/ProgressConfig/index.type.ts

[feature]:(WorkflowTemplate) support matching all users with execute permissions

---

src/api/common.d.ts
src/api/rule_template/index.d.ts
src/api/rule_template/index.ts
src/locale/zh-CN/ruleTemplate.ts
src/page/GlobalRuleTemplate/ImportRuleTemplate/ImportRuleTemplate.tsx
src/page/GlobalRuleTemplate/ImportRuleTemplate/__test__/ImportRuleTemplate.test.tsx
src/page/GlobalRuleTemplate/ImportRuleTemplate/__test__/__snapshots__/ImportRuleTemplate.test.tsx.snap
src/page/GlobalRuleTemplate/ImportRuleTemplate/index.tsx
src/page/GlobalRuleTemplate/RuleTemplateList/__snapshots__/index.test.tsx.snap
src/page/GlobalRuleTemplate/RuleTemplateList/column.tsx
src/page/GlobalRuleTemplate/RuleTemplateList/index.test.tsx
src/page/GlobalRuleTemplate/RuleTemplateList/index.tsx
src/page/GlobalRuleTemplate/__snapshots__/index.test.tsx.snap
src/page/GlobalRuleTemplate/index.tsx
src/page/RuleTemplate/ImportRuleTemplate/ImportRuleTemplate.tsx
src/page/RuleTemplate/ImportRuleTemplate/__test__/ImportRuleTemplate.test.tsx
src/page/RuleTemplate/ImportRuleTemplate/__test__/__snapshots__/ImportRuleTemplate.test.tsx.snap
src/page/RuleTemplate/ImportRuleTemplate/index.tsx
src/page/RuleTemplate/RuleTemplateList/__snapshots__/index.test.tsx.snap
src/page/RuleTemplate/RuleTemplateList/column.tsx
src/page/RuleTemplate/RuleTemplateList/index.test.tsx
src/page/RuleTemplate/RuleTemplateList/index.tsx
src/page/RuleTemplate/__snapshots__/index.test.tsx.snap
src/page/RuleTemplate/index.tsx

[feature]: support for rule template import and export

---

src/locale/zh-CN/workflowTemplate.ts
src/page/WorkflowTemplate/UpdateWorkflowTemplate/__snapshots__/index.test.tsx.snap
src/page/WorkflowTemplate/WorkflowTemplateForm/ProgressConfig/__snapshots__/index.test.tsx.snap
src/page/WorkflowTemplate/WorkflowTemplateForm/ProgressConfig/index.test.tsx
src/page/WorkflowTemplate/WorkflowTemplateForm/ProgressConfig/index.tsx
src/page/WorkflowTemplate/WorkflowTemplateForm/ProgressConfig/index.type.ts
src/page/WorkflowTemplate/WorkflowTemplateForm/__snapshots__/index.test.tsx.snap
src/page/WorkflowTemplate/WorkflowTemplateForm/index.test.tsx

[fix]: align the business logic of the executor

---

src/locale/zh-CN/ruleTemplate.ts
src/page/GlobalRuleTemplate/ImportRuleTemplate/ImportRuleTemplate.tsx
src/page/GlobalRuleTemplate/ImportRuleTemplate/__test__/ImportRuleTemplate.test.tsx
src/page/GlobalRuleTemplate/RuleTemplateList/index.test.tsx
src/page/GlobalRuleTemplate/RuleTemplateList/index.tsx
src/page/RuleTemplate/ImportRuleTemplate/ImportRuleTemplate.tsx
src/page/RuleTemplate/ImportRuleTemplate/__test__/ImportRuleTemplate.test.tsx
src/page/RuleTemplate/RuleTemplateList/index.test.tsx
src/page/RuleTemplate/RuleTemplateList/index.tsx

[fix]: fixing export file data flow types and importing file data formats

---

src/page/GlobalRuleTemplate/CreateRuleTemplate/index.tsx
src/page/GlobalRuleTemplate/ImportRuleTemplate/ImportRuleTemplate.tsx
src/page/GlobalRuleTemplate/RuleTemplateForm/BaseInfoForm/index.test.tsx
src/page/GlobalRuleTemplate/RuleTemplateForm/BaseInfoForm/index.tsx
src/page/GlobalRuleTemplate/RuleTemplateForm/BaseInfoForm/index.type.ts
src/page/GlobalRuleTemplate/RuleTemplateForm/index.tsx
src/page/GlobalRuleTemplate/RuleTemplateForm/index.type.ts
src/page/GlobalRuleTemplate/UpdateRuleTemplate/index.tsx
src/page/RuleTemplate/CreateRuleTemplate/index.tsx
src/page/RuleTemplate/ImportRuleTemplate/ImportRuleTemplate.tsx
src/page/RuleTemplate/ImportRuleTemplate/__test__/ImportRuleTemplate.test.tsx
src/page/RuleTemplate/RuleTemplateForm/BaseInfoForm/index.test.tsx
src/page/RuleTemplate/RuleTemplateForm/BaseInfoForm/index.tsx
src/page/RuleTemplate/RuleTemplateForm/BaseInfoForm/index.type.ts
src/page/RuleTemplate/RuleTemplateForm/index.test.tsx
src/page/RuleTemplate/RuleTemplateForm/index.tsx
src/page/RuleTemplate/RuleTemplateForm/index.type.ts
src/page/RuleTemplate/UpdateRuleTemplate/index.tsx

[fix]: fix the problem of importing templates to the global within the project and disable the database when importing templates type

---

src/locale/zh-CN/common.ts
src/locale/zh-CN/system.ts
src/locale/zh-CN/user.ts
src/page/System/DingTalkSetting/__snapshots__/index.test.tsx.snap
src/page/System/DingTalkSetting/index.test.tsx
src/page/System/DingTalkSetting/index.tsx
src/page/System/__snapshots__/index.test.tsx.snap
src/page/System/index.tsx
src/page/UserCenter/User/Modal/AddUser/index.test.tsx
src/page/UserCenter/User/Modal/AddUser/index.tsx
src/page/UserCenter/User/Modal/UpdateUser/index.test.tsx
src/page/UserCenter/User/Modal/UpdateUser/index.tsx
src/page/UserCenter/User/Modal/UserForm/__snapshots__/index.test.tsx.snap
src/page/UserCenter/User/Modal/UserForm/index.tsx
src/page/UserCenter/User/Modal/UserForm/index.type.ts
src/page/UserCenter/User/UserList/__snapshots__/index.test.tsx.snap
src/page/UserCenter/User/UserList/__testData__/index.ts
src/page/UserCenter/User/UserList/tableHeader.tsx
src/page/UserCenter/__test__/__snapshots__/UserCenter.test.tsx.snap
src/styles/tool.less
src/utils/FormRule.ts
src/utils/test/FormRule.test.ts

[fetaure]:support docking dingTalk

---

src/components/Nav/Header/Component/HeaderMenu.tsx
src/components/Nav/Header/Component/ProjectDropdown.tsx
src/components/Nav/Header/Component/__test__/HeaderMenu.test.tsx
src/components/Nav/Header/Component/__test__/ProjectDropdown.test.tsx
src/components/Nav/Header/Component/__test__/__snapshots__/HeaderMenu.test.tsx.snap
src/components/Nav/Header/Component/__test__/__snapshots__/ProjectDropdown.test.tsx.snap
src/components/Nav/Header/index.test.tsx
src/components/Nav/index.less
src/data/EmitterKey.ts
src/data/StorageKey.ts
src/locale/zh-CN/projectManage.ts
src/page/Order/Create/__snapshots__/index.test.tsx.snap
src/page/ProjectManage/ProjectDetail/index.test.tsx
src/page/ProjectManage/ProjectDetail/index.tsx
src/page/ProjectManage/ProjectList/__snapshots__/index.test.tsx.snap
src/page/ProjectManage/ProjectList/column.tsx
src/page/ProjectManage/ProjectList/index.test.tsx
src/page/ProjectManage/ProjectList/index.tsx
src/page/ProjectManage/__test__/utils.ts
src/theme/dark.ts
src/theme/index.ts
src/theme/light.ts
src/types/theme.type.ts

[feature]: support for quick navigation of project pages

---

src/components/Nav/Header/Component/ProjectDropdown.tsx
src/components/Nav/Header/Component/__test__/__snapshots__/HeaderMenu.test.tsx.snap
src/components/Nav/Header/Component/__test__/__snapshots__/ProjectDropdown.test.tsx.snap
src/page/Member/MemberGroupList/__test__/__snapshots__/index.test.tsx.snap
src/page/Member/MemberGroupList/column.tsx

actiontech/sqle#1212
actiontech/sqle#1219

[fix]: project navigation style tuning and fixing faulty text

---

src/components/Nav/Header/Component/HeaderMenu.tsx
src/components/Nav/Header/Component/ProjectNavigation.tsx
src/components/Nav/Header/Component/__test__/ProjectNavigation.test.tsx
src/components/Nav/Header/Component/__test__/__snapshots__/ProjectNavigation.test.tsx.snap
src/hooks/useCurrentUser/index.test.ts
src/hooks/useCurrentUser/index.ts
src/page/ProjectManage/ProjectDetail/index.test.tsx
src/page/ProjectManage/ProjectDetail/index.tsx
src/page/ProjectManage/ProjectList/index.test.tsx

[bugfix]: resolve the problem of different users using the same recently used project cache data

---

src/hooks/useMonacoEditor/index.test.tsx
src/hooks/useMonacoEditor/index.tsx
src/page/Order/SqlStatementFormTabs/SqlStatementForm.tsx
src/page/ProjectManage/ProjectList/__snapshots__/index.test.tsx.snap
src/page/ProjectManage/ProjectList/column.tsx

[fix]: Adjust the time format and fix the MonacoEditor bug

---

src/page/Member/MemberGroupList/index.tsx
src/page/Member/MemberList/index.tsx

[fix]:(Member) Fixing table pagination error

---

src/api/audit_plan/index.d.ts
src/api/audit_whitelist/index.d.ts
src/api/common.d.ts
src/api/common.enum.ts
src/api/instance/index.d.ts
src/api/project/index.d.ts
src/api/role/index.d.ts
src/api/rule_template/index.d.ts
src/api/task/index.d.ts
src/api/user/index.d.ts
src/api/user_group/index.d.ts
src/api/workflow/index.d.ts
src/page/System/DingTalkSetting/__snapshots__/index.test.tsx.snap
src/page/System/DingTalkSetting/index.tsx

[chore]: Optimize DingTalk configuration

---

src/api/audit_plan/index.d.ts
src/api/audit_whitelist/index.d.ts
src/api/common.d.ts
src/api/common.enum.ts
src/api/instance/index.d.ts
src/api/project/index.d.ts
src/api/role/index.d.ts
src/api/rule_template/index.d.ts
src/api/task/index.d.ts
src/api/user/index.d.ts
src/api/user_group/index.d.ts
src/api/workflow/index.d.ts
src/locale/zh-CN/system.ts
src/page/System/DingTalkSetting/index.tsx
src/page/System/GlobalSetting/__snapshots__/index.test.tsx.snap
src/page/System/GlobalSetting/index.test.tsx
src/page/System/GlobalSetting/index.tsx

[feature]: Support for configuring the url address of the project

---

src/api/common.d.ts
src/api/common.enum.ts
src/hooks/useAuditPlanTypes/index.test.tsx
src/hooks/useRoutes/__snapshots__/index.test.tsx.snap
src/hooks/useRoutes/index.tsx
src/locale/zh-CN/menu.ts
src/page/ProjectManage/ProjectDetail/Layout/Layout.tsx
src/page/ProjectManage/ProjectDetail/Layout/__test__/__snapshots__/index.test.tsx.snap
src/page/ProjectManage/ProjectDetail/Layout/index.tsx
src/router/config.tsx
src/testUtils/mockRequest.ts
src/types/router.type.ts

[feature]:Support for auditPlan menus to display instance types

---

src/api/common.d.ts
src/api/configuration/index.d.ts
src/api/configuration/index.ts
src/locale/zh-CN/system.ts
src/page/System/DingTalkSetting/__snapshots__/index.test.tsx.snap
src/page/System/DingTalkSetting/index.test.tsx
src/page/System/DingTalkSetting/index.tsx

[feature]: add test DingTalk

---

src/page/DataSource/DataSourceList/index.test.tsx
src/page/DataSource/DataSourceList/index.tsx

[bugfix]: refresh table after deleting DataSource

---

src/page/Order/AuditResult/__test__/AuditResultCollection.test.tsx
src/page/Order/AuditResult/column.tsx

[fix]: Disable the execute button when the order is canceled

---

src/api/common.d.ts
src/api/instance/index.d.ts
src/api/instance/index.ts
src/api/workflow/index.d.ts
src/api/workflow/index.ts
src/locale/zh-CN/order.ts
src/page/Order/Detail/Modal/OrderHistory/__snapshots__/index.test.tsx.snap
src/page/Order/Detail/Modal/OrderHistory/index.tsx
src/page/Order/Detail/OrderSteps/__test__/__snapshots__/index.test.tsx.snap
src/page/Order/Detail/OrderSteps/__test__/index.test.tsx
src/page/Order/Detail/OrderSteps/__test__/testData.ts
src/page/Order/Detail/OrderSteps/__test__/useGenerateOrderStepInfo.test.tsx
src/page/Order/Detail/OrderSteps/index.tsx
src/page/Order/Detail/OrderSteps/index.type.ts
src/page/Order/Detail/OrderSteps/useGenerateOrderStepInfo.tsx
src/page/Order/Detail/__snapshots__/index.test.tsx.snap
src/page/Order/Detail/hooks/__test__/useGenerateOrderStepsProps.test.ts
src/page/Order/Detail/hooks/useGenerateOrderStepsProps.ts
src/page/Order/Detail/index.tsx

[feature]: Support for sync order finished

---

src/api/common.d.ts
src/api/instance/index.d.ts
src/api/instance/index.ts
src/api/workflow/index.d.ts
src/api/workflow/index.ts
src/page/DataSource/AddDataSource/index.test.tsx
src/page/DataSource/AddDataSource/index.tsx

[feature]: Upgrade to create DataSource api

---

src/api/common.enum.ts
src/api/task/index.enum.ts
src/hooks/useStaticStatus/index.data.ts
src/locale/zh-CN/audit.ts
src/locale/zh-CN/order.ts
src/page/Order/AuditResult/InstanceTasksStatus.tsx
src/page/Order/AuditResult/__test__/InstanceTasksStatus.test.tsx
src/page/Order/AuditResult/__test__/__snapshots__/InstanceTasksStatus.test.tsx.snap

[feature]: Support for displaying manual executed status

---

src/data/EmitterKey.ts
src/page/AuditPlan/CreatePlan/__snapshots__/index.test.tsx.snap
src/page/AuditPlan/CreatePlan/index.test.tsx
src/page/AuditPlan/PlanForm/DataSource/DataSource.tsx
src/page/AuditPlan/PlanForm/__snapshots__/index.test.tsx.snap
src/page/AuditPlan/PlanForm/index.test.tsx
src/page/AuditPlan/PlanForm/index.tsx
src/page/AuditPlan/UpdatePlan/__snapshots__/index.test.tsx.snap
src/page/AuditPlan/UpdatePlan/index.test.tsx

[feature]: Supports filtering of data sources after selecting database types

---

src/locale/zh-CN/system.ts

[chore]: text adjustment

---

src/locale/zh-CN/order.ts
src/page/Order/Detail/OrderSteps/__test__/__snapshots__/index.test.tsx.snap
src/page/Order/Detail/OrderSteps/__test__/index.test.tsx
src/page/Order/Detail/OrderSteps/index.tsx
src/page/Order/Detail/OrderSteps/useGenerateOrderStepInfo.tsx
src/page/Order/Detail/__snapshots__/index.test.tsx.snap
src/page/Order/Detail/index.test.tsx

[feature]: Add secondary confirm for order operations

---

src/page/DataSource/AddDataSource/__snapshots__/index.test.tsx.snap
src/page/DataSource/AddDataSource/index.test.tsx
src/page/DataSource/DataSourceForm/index.tsx
src/page/DataSource/UpdateDataSource/__snapshots__/index.test.tsx.snap
src/page/DataSource/UpdateDataSource/index.test.tsx
src/page/DataSource/UpdateDataSource/index.tsx

[bugfix]: Hide audit levels when SQL queries do not need to be audited

---

src/locale/zh-CN/system.ts
src/page/GlobalRuleTemplate/ImportRuleTemplate/ImportRuleTemplate.tsx
src/page/GlobalRuleTemplate/ImportRuleTemplate/__test__/__snapshots__/ImportRuleTemplate.test.tsx.snap
src/page/Order/Detail/__snapshots__/index.test.tsx.snap
src/page/Order/Detail/index.tsx
src/page/RuleTemplate/ImportRuleTemplate/ImportRuleTemplate.tsx
src/page/RuleTemplate/ImportRuleTemplate/__test__/__snapshots__/ImportRuleTemplate.test.tsx.snap
src/page/WorkflowTemplate/UpdateWorkflowTemplate/__snapshots__/index.test.tsx.snap
src/page/WorkflowTemplate/WorkflowTemplateDetail/__snapshots__/index.test.tsx.snap
src/page/WorkflowTemplate/WorkflowTemplateDetail/index.test.tsx
src/page/WorkflowTemplate/WorkflowTemplateDetail/index.tsx
src/page/WorkflowTemplate/__testData__/index.ts

[ui]: page optimization

---

src/api/common.d.ts
src/page/Home/CommonTable/__snapshots__/index.test.tsx.snap
src/page/Home/CommonTable/column.tsx
src/page/Home/CommonTable/index.test.tsx
src/page/Home/RecentlyOrderPanel/column.tsx
src/page/Home/RecentlyOrderPanel/index.test.tsx

[fix]: (dashboard) order quick link error

---

src/locale/zh-CN/operationRecord.ts
src/page/OperationRecord/OperationRecordList/FilterForm.tsx
src/page/OperationRecord/OperationRecordList/__test__/FilterForm.test.tsx

add platform operation for project tips

---

src/locale/zh-CN/auditPlan.ts
src/page/AuditPlan/PlanList/__snapshots__/index.test.tsx.snap
src/page/AuditPlan/PlanList/tableColumn.tsx
src/page/ProjectManage/ProjectOverview/__test__/index.test.tsx
src/page/ProjectManage/ProjectOverview/index.tsx

[ui]: Add prompts and support quick jumps for project overview

---

src/page/Order/AuditResult/AuditResultCollection.tsx
src/page/Order/AuditResult/column.tsx

[fix]: Fixing  schedule time missing params

---

src/page/DataSource/UpdateDataSource/index.test.tsx
src/page/DataSource/UpdateDataSource/index.tsx

[fix]: Fixing update external data source parameter error

---

src/App.test.tsx
src/App.tsx
src/api/user/index.d.ts
src/api/user/index.ts
src/components/Nav/Header/Component/UserNavigation.tsx
src/components/Nav/Header/Component/__test__/UserNavigation.test.tsx
src/data/common.ts
src/hooks/useCurrentUser/index.test.ts
src/hooks/useUserInfo/index.test.ts
src/hooks/useUserInfo/index.ts
src/page/Account/Modal/ModifyPassword/index.test.tsx
src/page/Account/Modal/ModifyPassword/index.tsx
src/page/Login/index.test.tsx
src/page/Login/index.tsx
src/page/ProjectManage/ProjectDetail/ProjectDetail.tsx
src/page/ProjectManage/ProjectDetail/index.test.tsx
src/page/SqlQuery/index.test.tsx
src/page/SqlQuery/index.tsx
src/utils/Api.ts
src/utils/Common.ts
src/utils/test/api.test.ts
src/utils/test/common.test.ts

[feature]: Upgrade login interface and optimize page jumps

---

src/api/common.enum.ts
src/page/OperationRecord/OperationRecordList/__test__/List.test.tsx
src/page/OperationRecord/OperationRecordList/column.tsx
src/page/SyncDataSource/SyncTaskList/column.tsx
src/page/SyncDataSource/SyncTaskList/index.test.tsx

actiontech/sqle#1281
actiontech/sqle#1278

[chore]: build api and update enum

---

src/api/common.d.ts
src/hooks/useOperationActions/__snapshots__/index.test.tsx.snap
src/hooks/useOperationActions/index.test.tsx
src/hooks/useOperationActions/index.tsx
src/page/OperationRecord/OperationRecordList/FilterForm.tsx
src/page/OperationRecord/OperationRecordList/__test__/FilterForm.test.tsx
src/page/OperationRecord/OperationRecordList/__test__/List.test.tsx
src/page/OperationRecord/OperationRecordList/__test__/__snapshots__/FilterForm.test.tsx.snap
src/testUtils/mockRequest.ts

[feat]: Support for filtering action content by selecting operation type

---

src/locale/zh-CN/order.ts
src/page/Order/AuditResult/__test__/AuditResultCollection.test.tsx
src/page/Order/AuditResult/column.tsx

[feat]: Add secondary confirm for sql execute

---

src/api/OperationRecord/index.d.ts
src/api/OperationRecord/index.ts
src/locale/zh-CN/operationRecord.ts
src/page/OperationRecord/OperationRecordList/FilterForm.tsx
src/page/OperationRecord/OperationRecordList/List.tsx
src/page/OperationRecord/OperationRecordList/__test__/FilterForm.test.tsx
src/page/OperationRecord/OperationRecordList/__test__/List.test.tsx
src/page/OperationRecord/OperationRecordList/__test__/__snapshots__/List.test.tsx.snap
src/page/OperationRecord/OperationRecordList/index.tsx

[feat]: Add export operation record list

---

src/api/common.d.ts
src/api/configuration/index.d.ts
src/api/configuration/index.ts
src/locale/zh-CN/system.ts
src/page/System/LarkSetting/__snapshots__/index.test.tsx.snap
src/page/System/LarkSetting/index.test.tsx
src/page/System/LarkSetting/index.tsx
src/page/System/__snapshots__/index.test.tsx.snap
src/page/System/index.tsx

[feat]: Support for lark to push order messages

---

src/page/Order/Detail/Modal/ModifySqlModal/__snapshots__/index.test.tsx.snap
src/page/Order/Detail/Modal/ModifySqlModal/index.test.tsx
src/page/Order/Detail/Modal/ModifySqlModal/index.tsx
src/page/Order/Detail/__snapshots__/index.test.tsx.snap
src/page/Order/Detail/hooks/__test__/useInitDataWithRequest.test.ts
src/page/Order/Detail/hooks/__test__/useModifySql.test.tsx
src/page/Order/Detail/hooks/useInitDataWithRequest.ts
src/page/Order/Detail/hooks/useModifySql.ts
src/page/Order/Detail/index.tsx

[fix]: open monaco again that is not rendered properly

---

src/locale/zh-CN/order.ts
src/page/Order/Detail/index.test.tsx
src/page/Order/Detail/index.tsx

[feat]: Prompt information after successfully closing the order

---

src/locale/zh-CN/auditPlan.ts
src/locale/zh-CN/dataSource.ts
src/page/DataSource/AddDataSource/__snapshots__/index.test.tsx.snap
src/page/DataSource/DataSourceForm/index.tsx
src/page/DataSource/UpdateDataSource/__snapshots__/index.test.tsx.snap

[ui]: Change text description

---

src/api/OperationRecord/index.d.ts
src/api/OperationRecord/index.ts
src/api/workflow/index.d.ts
src/api/workflow/index.enum.ts
src/api/workflow/index.ts
src/locale/zh-CN/order.ts
src/page/Order/List/__snapshots__/index.test.tsx.snap
src/page/Order/List/index.test.tsx
src/page/Order/List/index.tsx

[feature]: Support export order list

---

src/App.test.tsx
src/App.tsx
src/components/Nav/Header/Component/UserNavigation.tsx
src/components/Nav/Header/Component/__test__/UserNavigation.test.tsx
src/hooks/useUserInfo/index.test.ts
src/hooks/useUserInfo/index.ts
src/index.tsx
src/page/Account/Modal/ModifyPassword/index.test.tsx
src/page/Account/index.test.tsx
src/page/ProjectManage/ProjectDetail/index.test.tsx
src/utils/test/api.test.ts

[feat]: Support for quick redirection after login

---

src/page/System/LarkSetting/LarkSetting.tsx
src/page/System/LarkSetting/__snapshots__/index.test.tsx.snap
src/page/System/LarkSetting/index.test.tsx

[chore]: Change label text

---

src/page/UserCenter/User/Modal/UpdateUser/__snapshots__/index.test.tsx.snap
src/page/UserCenter/User/Modal/UpdateUser/index.test.tsx
src/page/UserCenter/User/Modal/UpdateUser/index.tsx

[fix]: UpdateUser form not set "is_diabled" value

---

src/page/System/index.tsx

[featuer]: WeChat push work order supports community

---

src/locale/zh-CN/system.ts

[ui]: Change text describe

---

src/api/common.d.ts
src/locale/zh-CN/account.ts
src/locale/zh-CN/user.ts
src/page/Account/UserPhone/Phone.tsx
src/page/Account/UserPhone/__snapshots__/index.test.tsx.snap
src/page/Account/UserPhone/index.test.tsx
src/page/Account/UserPhone/index.tsx
src/page/Account/__snapshots__/index.test.tsx.snap
src/page/Account/index.tsx

[feature]: Support to modify user mobile phone

---

src/api/common.d.ts
src/api/dashboard/index.d.ts
src/api/dashboard/index.ts
src/locale/zh-CN/dashboard.ts
src/page/Home/CommonTable/Table.tsx
src/page/Home/CommonTable/__snapshots__/index.test.tsx.snap
src/page/Home/DBAPanel/index.test.tsx
src/page/Home/DBAPanel/index.tsx
src/page/Home/DBAPanel/index.type.ts
src/page/Home/DEVPanel/index.test.tsx
src/page/Home/DEVPanel/index.tsx
src/page/Home/DEVPanel/index.type.ts
src/page/Home/RecentlyOrderPanel/index.test.tsx
src/page/Home/RecentlyOrderPanel/index.tsx
src/page/Home/RecentlyOrderPanel/index.type.ts
src/page/Home/__snapshots__/index.test.tsx.snap
src/page/Home/index.test.tsx
src/page/Home/index.tsx
src/page/Home/useDashboardRequest.ts

[feature]: Support for filtering dashboard by project name

---

src/page/Home/index.tsx

[fix]: (Dashboard) Sort filter  porject items

---

src/page/RuleTemplate/RuleTemplateList/column.tsx
src/page/RuleTemplate/RuleTemplateList/index.test.tsx
src/page/RuleTemplate/RuleTemplateList/index.tsx

[feature]: Hide some features when current project is archived

---

src/page/Home/index.tsx

[fix]: (Dashboard) remove Badge's showZero prop

---

src/components/Nav/Header/Component/Logo.tsx
src/components/Nav/Header/Component/__test__/__snapshots__/Logo.test.tsx.snap
src/components/Nav/Header/__snapshots__/index.test.tsx.snap
src/components/Nav/__snapshots__/index.test.tsx.snap
src/locale/zh-CN/common.ts
src/page/DataSource/DataSourceList/columns.tsx
src/page/ProjectManage/ProjectDetail/ProjectDetail.tsx

actiontech/sqle#1375
actiontech/sqle#1374

[fix]: remove ee from title and refresh project details when project changes

---

src/page/System/License/index.test.tsx
src/page/System/License/index.tsx

[fix]: Get sqle license info set response type

---

src/page/System/LarkSetting/LarkSetting.tsx
src/page/System/LarkSetting/__snapshots__/index.test.tsx.snap
src/page/System/LarkSetting/index.test.tsx

Closes  to https://github.com/actiontech/sqle/issues/1400 & https://github.com/actiontech/sqle/issues/1401
fix Lark Setting issues

[fix]: fix Lark Setting issues

---

src/page/Order/AuditResult/AuditResultFilterForm.tsx
src/page/Order/AuditResult/column.tsx
src/page/Order/Detail/__snapshots__/index.test.tsx.snap

Closes to  https://github.com/actiontech/sqle/issues/1414

[ui]:remove audit_status column and filterForm in Oder Detail

---

src/components/RuleList/index.less
src/components/RuleList/index.tsx

Closes to https://github.com/actiontech/sqle/issues/1412

[fix]:fix ListItem render problem in RuleList

---

src/api/common.d.ts
src/api/instance/index.d.ts
src/api/instance/index.ts
src/page/Order/Create/SqlInfoForm/DatabaseInfo.tsx
src/page/Order/Create/SqlInfoForm/__test__/DatabaseInfo.test.tsx
src/page/Order/Create/SqlInfoForm/__test__/__snapshots__/DatabaseInfo.test.tsx.snap
src/page/Order/Create/SqlInfoForm/__test__/__snapshots__/index.test.tsx.snap
src/page/Order/Create/SqlInfoForm/__test__/index.test.tsx
src/page/Order/Create/SqlInfoForm/index.type.ts
src/page/Order/Create/__snapshots__/index.test.tsx.snap
src/page/Order/Create/index.test.tsx

[feature]: Display the rules template used when creating order

---

src/page/Order/Create/__snapshots__/index.test.tsx.snap
src/page/Order/Create/index.test.tsx
src/page/Order/Create/index.tsx

[ui]: Adjust the max length of the order desc

---

package.json
src/components/BackendForm/BackendForm.test.tsx
src/components/EditText/EditText.test.tsx
src/components/Nav/Header/Component/__test__/HeaderMenu.test.tsx
src/hooks/useBack/index.test.ts
src/page/Account/UserEmail/index.test.tsx
src/page/Account/UserPhone/index.test.tsx
src/page/AuditPlan/PlanList/Modal/SubscribeNotice/tests/SubscribeNotice.test.tsx
src/page/DataSource/AddDataSource/index.test.tsx
src/page/Home/CommonTable/index.test.tsx
src/page/Member/MemberGroupList/__test__/FilterForm.test.tsx
src/page/Member/MemberList/__test__/FilterForm.test.tsx
src/page/Order/AuditResult/AuditResultCollection.tsx
src/page/Order/AuditResult/__test__/ScheduleTimeModal.test.tsx
src/page/Order/AuditResult/__test__/__snapshots__/ScheduleTimeModal.test.tsx.snap
src/page/ProjectManage/ProjectOverview/__test__/index.test.tsx
src/page/ReportStatistics/Panel/__test__/OrderQuantityTrend.test.tsx
src/page/ReportStatistics/Panel/__test__/__snapshots__/OrderQuantityTrend.test.tsx.snap
src/page/RuleTemplate/RuleTemplateList/column.tsx
src/page/SyncDataSource/SyncTaskList/index.test.tsx
src/page/SyncDataSource/__snapshots__/index.test.tsx.snap
src/page/SyncDataSource/index.tsx
src/router/config.tsx
src/testUtils/mockRouter.ts
src/types/common.type.ts
src/types/router.type.ts

[fix]: (SyncDataSrouce) Adjust the routing structure and remove unused import.
https://github.com/actiontech/sqle-ui/pull/259

[fix]: (SyncDataSrouce) Adjust ... cherry pick to 2304

---

src/api/common.d.ts
src/api/configuration/index.d.ts
src/api/configuration/index.ts
src/hooks/useDatabaseType/index.test.data.ts
src/hooks/useDatabaseType/index.test.tsx
src/hooks/useDatabaseType/index.tsx
src/page/DataSource/AddDataSource/index.test.tsx
src/page/DataSource/DataSourceForm/DatabaseFormItem/index.tsx
src/page/ReportStatistics/__test__/__snapshots__/index.test.tsx.snap
src/page/ReportStatistics/__test__/index.test.tsx
src/testUtils/mockRequest.ts

[feature]: Supports automatic switching of default ports based on data source type

---

CHANGELOG.md
src/components/CopyIcon/CopyIcon.test.tsx
src/components/CopyIcon/CopyIcon.tsx
src/components/CopyIcon/__snapshots__/CopyIcon.test.tsx.snap
src/components/CopyIcon/index.less
src/components/CopyIcon/index.tsx
src/locale/zh-CN/common.ts
src/page/Order/AuditResult/RenderExecuteSql.tsx
src/page/Order/AuditResult/__test__/RenderExecuteSql.test.tsx
src/page/Order/AuditResult/__test__/__snapshots__/AuditResultCollection.test.tsx.snap
src/page/Order/AuditResult/__test__/__snapshots__/RenderExecuteSql.test.tsx.snap
src/page/Order/AuditResult/__test__/__snapshots__/index.test.tsx.snap
src/page/Order/AuditResult/column.tsx
src/page/Order/AuditResult/index.type.ts
src/page/Order/Create/__snapshots__/index.test.tsx.snap
src/page/Order/Detail/__snapshots__/index.test.tsx.snap
src/utils/Copy.ts
src/utils/test/Copy.test.ts

[fix]: support hight light sql and copy

---

src/components/Nav/Header/Component/__test__/ProjectNavigation.test.tsx
src/hooks/useBackendTable/__snapshots__/useBackendTable.test.tsx.snap
src/hooks/useBackendTable/useBackendTable.tsx
src/locale/zh-CN/common.ts
src/page/Home/CommonTable/__snapshots__/index.test.tsx.snap
src/page/Home/CommonTable/column.tsx
src/page/Home/DBAPanel/__snapshots__/index.test.tsx.snap
src/page/Home/DEVPanel/__snapshots__/index.test.tsx.snap
src/page/Home/RecentlyOrderPanel/__snapshots__/index.test.tsx.snap
src/page/Home/RecentlyOrderPanel/column.tsx
src/page/Home/__snapshots__/index.test.tsx.snap
src/page/Order/Create/index.test.tsx
src/page/Order/Create/index.tsx
src/page/Order/List/__snapshots__/index.test.tsx.snap
src/page/Order/List/column.tsx
src/page/Order/SqlStatementFormTabs/SqlStatementFormTabs.tsx
src/page/SqlAnalyze/AuditPlan/__snapshots__/index.test.tsx.snap
src/page/SqlAnalyze/Order/__snapshots__/index.test.tsx.snap
src/page/SqlAnalyze/SqlAnalyze/__snapshots__/SqlAnalyze.test.tsx.snap
src/page/SqlAnalyze/SqlAnalyze/__snapshots__/useTableSchema.test.tsx.snap

[fix]: optimize order desc column and modify workflow name reg

---

CHANGELOG.md
src/api/task/index.enum.ts
src/api/workflow/index.d.ts
src/api/workflow/index.ts
src/hooks/useStaticStatus/__snapshots__/index.test.tsx.snap
src/hooks/useStaticStatus/index.data.ts
src/hooks/useStaticStatus/index.tsx
src/locale/zh-CN/audit.ts
src/locale/zh-CN/order.ts
src/page/Order/AuditResult/AuditResultCollection.tsx
src/page/Order/AuditResult/__test__/AuditResultCollection.test.tsx
src/page/Order/AuditResult/__test__/__snapshots__/AuditResultCollection.test.tsx.snap
src/page/Order/AuditResult/column.tsx
src/page/Order/Detail/Modal/OrderHistory/__snapshots__/index.test.tsx.snap
src/page/Order/Detail/Modal/OrderHistory/index.tsx
src/page/Order/Detail/OrderSteps/__test__/__snapshots__/index.test.tsx.snap
src/page/Order/Detail/OrderSteps/__test__/__snapshots__/useGenerateOrderStepInfo.test.tsx.snap
src/page/Order/Detail/OrderSteps/__test__/index.test.tsx
src/page/Order/Detail/OrderSteps/__test__/testData.ts
src/page/Order/Detail/OrderSteps/__test__/useGenerateOrderStepInfo.test.tsx
src/page/Order/Detail/OrderSteps/index.tsx
src/page/Order/Detail/OrderSteps/index.type.ts
src/page/Order/Detail/OrderSteps/useGenerateOrderStepInfo.tsx
src/page/Order/Detail/__snapshots__/index.test.tsx.snap
src/page/Order/Detail/hooks/__test__/useGenerateOrderStepsProps.test.ts
src/page/Order/Detail/hooks/useGenerateOrderStepsProps.ts
src/page/Order/Detail/index.tsx

[feature]: Support terminate workflow

---

src/api/workflow/index.d.ts
src/api/workflow/index.ts

[chore]: rebuild api

---

src/api/common.enum.ts
src/locale/zh-CN/order.ts
src/page/Order/AuditResult/InstanceTasksStatus.tsx
src/page/Order/AuditResult/__test__/InstanceTasksStatus.test.tsx
src/page/Order/AuditResult/__test__/__snapshots__/InstanceTasksStatus.test.tsx.snap
src/page/Order/AuditResult/index.type.ts

[feature]:  order status support show terminate

---

src/api/common.enum.ts
src/api/task/index.enum.ts
src/hooks/useStaticStatus/__snapshots__/index.test.tsx.snap
src/hooks/useStaticStatus/index.data.ts
src/locale/zh-CN/audit.ts
src/locale/zh-CN/order.ts
src/page/Order/AuditResult/InstanceTasksStatus.tsx
src/page/Order/AuditResult/__test__/InstanceTasksStatus.test.tsx
src/page/Order/AuditResult/__test__/__snapshots__/InstanceTasksStatus.test.tsx.snap

[chore]: Modify enum

---

src/page/Order/AuditResult/RenderExecuteSql.tsx
src/styles/component.less

related to[ issue-1508](https://github.com/actiontech/sqle/issues/1508)

[fix]: fix rollback sql tips' overflow bug

---

src/api/common.d.ts
src/locale/zh-CN/system.ts
src/page/System/SMTPSetting/__snapshots__/index.test.tsx.snap
src/page/System/SMTPSetting/index.test.tsx
src/page/System/SMTPSetting/index.tsx

[feature]: Add configuration option to disable SSL security verification

---

src/locale/zh-CN/member.ts
src/page/Member/MemberList/__test__/__snapshots__/index.test.tsx.snap
src/page/Member/MemberList/__test__/index.test.tsx
src/page/Member/MemberList/column.tsx
src/page/Member/Modal/AddMember.tsx
src/page/Member/Modal/MemberForm.tsx
src/page/Member/Modal/UpdateMember.tsx
src/page/Member/Modal/__test__/AddMember.test.tsx
src/page/Member/Modal/__test__/MemberForm.test.tsx
src/page/Member/Modal/__test__/UpdateMember.test.tsx
src/page/Member/Modal/__test__/__snapshots__/MemberForm.test.tsx.snap
src/page/Member/Modal/index.type.ts

[feature]: Set member as project admin without requiring data source and operation permissions

---

CHANGELOG.md
src/api/common.d.ts
src/locale/zh-CN/system.ts
src/page/System/GlobalSetting/__snapshots__/index.test.tsx.snap
src/page/System/GlobalSetting/index.test.tsx
src/page/System/GlobalSetting/index.tsx

[feature]: Support configuring the expiration time of operation record

---

CHANGELOG.md
src/locale/zh-CN/order.ts
src/page/Order/Create/SqlInfoForm/__test__/__snapshots__/index.test.tsx.snap
src/page/Order/Create/SqlInfoForm/__test__/index.test.tsx
src/page/Order/Create/SqlInfoForm/index.tsx
src/page/Order/Create/__snapshots__/index.test.tsx.snap
src/page/Order/Detail/Modal/ModifySqlModal/__snapshots__/index.test.tsx.snap
src/page/Order/Detail/Modal/ModifySqlModal/index.test.tsx
src/page/Order/Detail/Modal/ModifySqlModal/index.tsx
src/page/Order/Detail/__testData__/index.tsx
src/utils/FormatterSQL.ts
src/utils/test/FormatSQL.test.ts
src/utils/test/__snapshots__/FormatSQL.test.ts.snap

[fix]: Format SQL statements based on database type

---

src/locale/zh-CN/common.ts

[chore]: update button text [skip ci]

---

CHANGELOG.md
src/page/Order/Create/SqlInfoForm/DatabaseInfo.tsx
src/page/Order/Create/SqlInfoForm/__test__/DatabaseInfo.test.tsx
src/page/System/WebhookSetting/Webhook.tsx
src/page/System/WebhookSetting/__snapshots__/Webhook.test.tsx.snap
src/page/System/Wechat/Wechat.test.tsx
src/page/System/Wechat/Wechat.tsx

[fix]: Wenhook wrong text and correctly display the results of testing the WeChat push function

---

src/locale/zh-CN/customRule.ts
src/page/CustomRule/CreateCustomRule/__snapshots__/index.test.tsx.snap
src/page/CustomRule/CustomRuleForm/EditRuleScript.tsx
src/page/CustomRule/CustomRuleForm/__tests__/__snapshots__/EditRuleScript.test.tsx.snap
src/page/CustomRule/UpdateCustomRule/__snapshots__/index.test.tsx.snap

[chore]:  Adjust fotter button wrapper width

---

src/locale/en-US/audit.ts
src/locale/en-US/dataSource.ts
src/locale/zh-CN/audit.ts
src/locale/zh-CN/dataSource.ts
src/page/Order/AuditResult/AuditResultFilterForm.tsx
src/page/Order/AuditResult/__test__/__snapshots__/AuditResultCollection.test.tsx.snap
src/page/Order/AuditResult/__test__/__snapshots__/index.test.tsx.snap
src/page/Order/Create/__snapshots__/index.test.tsx.snap
src/page/Order/Detail/__snapshots__/index.test.tsx.snap
src/page/System/DingTalkSetting/__snapshots__/index.test.tsx.snap
src/page/System/DingTalkSetting/index.test.tsx
src/page/System/DingTalkSetting/index.tsx
src/page/System/LarkSetting/LarkSetting.tsx
src/page/System/LarkSetting/__snapshots__/index.test.tsx.snap
src/page/System/SMTPSetting/__snapshots__/index.test.tsx.snap
src/page/System/SMTPSetting/index.tsx
src/page/System/WebhookSetting/Webhook.test.tsx
src/page/System/WebhookSetting/Webhook.tsx
src/page/System/WebhookSetting/__snapshots__/Webhook.test.tsx.snap
src/page/System/Wechat/Wechat.test.tsx
src/page/System/Wechat/Wechat.tsx
src/page/System/Wechat/__snapshots__/Wechat.test.tsx.snap
src/page/System/hooks/useConditionalConfig.tsx

close to [issue-1658 1-3](https://github.com/actiontech/sqle/issues/1658)

[chore]: Optimize some page

---

CHANGELOG.md
src/api/common.d.ts
src/api/instance/index.d.ts
src/api/instance/index.ts
src/api/sql_analysis/index.d.ts
src/components/RuleList/__snapshots__/index.test.tsx.snap
src/components/RuleList/index.test.tsx
src/components/RuleList/index.tsx
src/locale/zh-CN/customRule.ts
src/page/CustomRule/CreateCustomRule/__snapshots__/index.test.tsx.snap
src/page/CustomRule/CreateCustomRule/index.tsx
src/page/CustomRule/CustomRuleForm/BaseInfoForm.tsx
src/page/CustomRule/CustomRuleForm/__tests__/__snapshots__/BaseInfoForm.test.tsx.snap
src/page/CustomRule/UpdateCustomRule/__snapshots__/index.test.tsx.snap
src/page/CustomRule/UpdateCustomRule/index.tsx
src/page/GlobalRuleTemplate/CreateRuleTemplate/index.test.tsx
src/page/GlobalRuleTemplate/CreateRuleTemplate/index.tsx
src/page/GlobalRuleTemplate/UpdateRuleTemplate/index.test.tsx
src/page/GlobalRuleTemplate/UpdateRuleTemplate/index.tsx
src/page/Rule/__testData__/index.ts
src/page/RuleTemplate/CreateRuleTemplate/index.test.tsx
src/page/RuleTemplate/CreateRuleTemplate/index.tsx
src/page/RuleTemplate/UpdateRuleTemplate/index.test.tsx
src/page/RuleTemplate/UpdateRuleTemplate/index.tsx

[fix]: Finish CustomRule page

---

CHANGELOG.md
src/page/System/LDAPSetting/index.tsx
src/page/System/LarkSetting/LarkSetting.tsx
src/page/System/LarkSetting/index.test.tsx
src/page/System/SMTPSetting/__snapshots__/index.test.tsx.snap
src/page/System/SMTPSetting/index.test.tsx
src/page/System/SMTPSetting/index.tsx
src/page/System/Wechat/Wechat.test.tsx
src/page/System/Wechat/Wechat.tsx
src/page/System/Wechat/__snapshots__/Wechat.test.tsx.snap

[fix]: Supplementary unit test, test WeChat configuration and add validation

---

src/page/CustomRule/CreateCustomRule/__snapshots__/index.test.tsx.snap
src/page/CustomRule/CreateCustomRule/index.tsx
src/page/CustomRule/UpdateCustomRule/index.tsx

[fix]: Fix the problem of the order of form validation and start execution

---

CHANGELOG.md
src/locale/zh-CN/projectManage.ts
src/page/ProjectManage/ProjectOverview/Panel/OrderClassification.tsx
src/page/ProjectManage/ProjectOverview/Panel/__test__/__snapshots__/OrderClassification.test.tsx.snap
src/page/ProjectManage/ProjectOverview/Panel/__test__/mockApi.ts
src/page/ProjectManage/ProjectOverview/__test__/__snapshots__/index.test.tsx.snap

[feature]: order info chart added execting status

---

src/api/configuration/index.d.ts
src/api/configuration/index.ts
src/locale/zh-CN/system.ts
src/page/System/LarkAuditSetting/__snapshots__/index.test.tsx.snap
src/page/System/LarkAuditSetting/index.test.tsx
src/page/System/LarkAuditSetting/index.tsx
src/page/System/__snapshots__/index.test.tsx.snap
src/page/System/index.tsx

[actiontech/sqle#](https://github.com/actiontech/sqle-ee/issues/901)

[feature]: Add Feishu configuration to process connection settings

---

src/api/common.d.ts
src/api/rule_template/index.d.ts
src/api/rule_template/index.ts
src/api/sql_audit_record/index.d.ts
src/api/sql_audit_record/index.ts
src/page/SqlAuditRecord/Create/BaseInfoForm.tsx
src/page/SqlAuditRecord/Create/SQLInfoForm.tsx
src/page/SqlAuditRecord/Create/index.tsx
src/page/SqlAuditRecord/Create/index.type.ts
src/page/SqlAuditRecord/List/CustomTags.tsx

[fix]: build api and add rule template link

---

craco.config.js
src/api/SqlManage/index.enum.ts
src/api/common.enum.ts
src/locale/zh-CN/common.ts
src/locale/zh-CN/sqlManagement.ts
src/page/SQLManagement/SQLPanel/FilterForm.tsx
src/page/SQLManagement/SQLPanel/UpdateSQLStatus.tsx
src/page/SQLManagement/SQLPanel/column.tsx
src/page/SQLManagement/SQLPanel/hooks/useStaticStatus.tsx
src/page/SQLManagement/SQLPanel/index.tsx
src/page/SqlAuditRecord/Create/BaseInfoForm.tsx
src/page/SqlAuditRecord/List/CustomTags.tsx
src/utils/FormRule.ts
src/utils/test/FormRule.test.ts

https://github.com/actiontech/sqle-ee/issues/943

[chore]: Optimize the SQL management page and add tag name rule

---

src/api/SqlManage/index.d.ts
src/api/SqlManage/index.enum.ts
src/api/SqlManage/index.ts
src/locale/zh-CN/sqlManagement.ts
src/page/SQLManagement/SQLPanel/index.tsx

https://github.com/actiontech/sqle-ee/issues/943

[feature]: Support export SQLManagement list

---

src/page/SqlAuditRecord/Create/SQLInfoForm.tsx
src/page/SqlAuditRecord/Create/index.tsx
src/page/SqlAuditRecord/Create/index.type.ts

[fix]: Fix missing Promise return causing button not disabled during request

---

src/api/common.d.ts
src/components/AuditResultErrorMessage/index.test.tsx
src/components/AuditResultErrorMessage/index.tsx
src/components/RuleList/index.tsx
src/page/Order/AuditResult/__test__/index.test.tsx
src/page/Order/Detail/__testData__/index.tsx
src/page/RuleKnowledge/RuleUnderstand/index.tsx
src/page/RuleKnowledge/RuleUnderstand/index.type.ts
src/page/RuleKnowledge/index.tsx

[actiontech/sqle](https://github.com/actiontech/sqle-ee/issues/1052)

[feature]: Enable custom rules support in the  rule knowledge

---

src/page/SQLManagement/SQLPanel/index.tsx

https://github.com/actiontech/sqle-ee/issues/1140

[fix]:(SQLManagement) non-admin users unable to export files

---

src/components/CopyIcon/CopyIcon.test.tsx
src/components/CopyIcon/CopyIcon.tsx

fix: https://github.com/actiontech/sqle/issues/1972

[fix]: Resolve text formatting loss issue during copying process

---

src/data/EmitterKey.ts
src/page/Order/Create/SqlInfoForm/index.tsx
src/page/Order/Create/index.test.tsx
src/page/Order/Create/index.tsx
src/page/Order/SqlStatementFormTabs/SqlStatementForm.tsx

Closes to [issue-2031](https://github.com/actiontech/sqle/issues/2031)

fix: fix uploadType reset bug

---

src/api/SqlManage/index.d.ts
src/api/common.d.ts
src/locale/zh-CN/sqlManagement.ts
src/page/SQLManagement/SQLPanel/FilterForm.tsx
src/page/SQLManagement/SQLPanel/column.tsx
src/page/SQLManagement/SQLPanel/index.less
src/page/SQLManagement/SQLPanel/index.tsx
src/page/SQLManagement/SQLPanel/index.type.ts

[ee-issue-1191](https://github.com/actiontech/sqle-ee/issues/1191)

[feature]: supply endpoint columns and filter

---

src/page/Order/AuditResult/index.tsx
src/page/Order/AuditResult/index.type.ts
src/page/SqlAuditRecord/Create/index.tsx

fix: [actiontech/sqle/issues/1973](https://github.com/actiontech/sqle/issues/1973)

[fix](sql audit):update created scroll position

---

src/page/SQLManagement/SQLPanel/column.tsx

closes to [ee-issue-1210](https://github.com/actiontech/sqle-ee/issues/1210)

[fix]: change sortDirections in SQLManager

---

src/data/common.ts
src/locale/zh-CN/sqlAudit.ts
src/page/Order/SqlStatementFormTabs/SqlStatementForm.tsx
src/page/SqlAuditRecord/Create/SQLInfoForm.tsx

Closes to [issue-2067](https://github.com/actiontech/sqle/issues/2067)

[fix](SqlStatmentForm & SqlInfoForm): supply validator for sqlStatement field

---

src/page/Order/AuditResult/__test__/index.test.tsx
src/page/Order/AuditResult/index.tsx
yarn.lock

cherry pick https://github.com/actiontech/sqle-ui/pull/358
issue:https://github.com/actiontech/sqle-ee/issues/1404

[fix](Order): Add responseType parameter to download
