actiontech/sqle-ui

package.json
src/components/BackendForm/BackendForm.test.tsx
src/components/EditText/EditText.test.tsx
src/components/Nav/Header/Component/__test__/HeaderMenu.test.tsx
src/hooks/useBack/index.test.ts
src/page/Account/UserEmail/index.test.tsx
src/page/Account/UserPhone/index.test.tsx
src/page/AuditPlan/PlanList/Modal/SubscribeNotice/tests/SubscribeNotice.test.tsx
src/page/DataSource/AddDataSource/index.test.tsx
src/page/Home/CommonTable/index.test.tsx
src/page/Member/MemberGroupList/__test__/FilterForm.test.tsx
src/page/Member/MemberList/__test__/FilterForm.test.tsx
src/page/Order/AuditResult/AuditResultCollection.tsx
src/page/Order/AuditResult/__test__/ScheduleTimeModal.test.tsx
src/page/Order/AuditResult/__test__/__snapshots__/ScheduleTimeModal.test.tsx.snap
src/page/ProjectManage/ProjectOverview/__test__/index.test.tsx
src/page/ReportStatistics/Panel/__test__/OrderQuantityTrend.test.tsx
src/page/ReportStatistics/Panel/__test__/__snapshots__/OrderQuantityTrend.test.tsx.snap
src/page/RuleTemplate/RuleTemplateList/column.tsx
src/page/SyncDataSource/SyncTaskList/index.test.tsx
src/page/SyncDataSource/__snapshots__/index.test.tsx.snap
src/page/SyncDataSource/index.tsx
src/router/config.tsx
src/testUtils/mockRouter.ts
src/types/common.type.ts
src/types/router.type.ts

[fix]: (SyncDataSrouce) Adjust the routing structure and remove unused import.

---

src/page/AuditPlan/UpdatePlan/index.test.tsx
src/page/AuditPlan/UpdatePlan/index.tsx

[fix]: Update audit plan param

---

CHANGELOG.md
src/page/Order/AuditResult/__test__/AuditResultCollection.test.tsx
src/page/Order/Detail/__snapshots__/index.test.tsx.snap
src/page/Order/Detail/__testData__/index.tsx
src/page/Order/Detail/index.test.tsx

[Order/Detail/__snapshots__/index.test.tsx.snap](https://github.com/actiontech/sqle-ui/compare/fix/test-snapshot-error?expand=1#diff-1514e3a0c3783db6fa11863148a502b452c9c90938acb92e881cd5c6c0f9b4cb) 出现快照更改的原因: mock 当前时间后 Spin 组件的快照会产生变更

[fix]: Pages snapshots inconsistent with different timestamps

---

CHANGELOG.md
src/locale/zh-CN/system.ts
src/page/System/Wechat/Wechat.tsx
src/page/System/Wechat/__snapshots__/Wechat.test.tsx.snap

[chore]: Add tips fro test wechat form

---

src/page/AuditPlan/PlanForm/index.tsx
src/page/DataSource/DataSourceForm/index.tsx
src/page/GlobalRuleTemplate/RuleTemplateForm/BaseInfoForm/index.tsx
src/page/RuleTemplate/RuleTemplateForm/BaseInfoForm/index.tsx
src/page/UserCenter/Role/Modal/RoleForm/index.tsx
src/page/UserCenter/User/Modal/UserForm/index.tsx
src/page/UserCenter/UserGroup/Modal/UserGroupForm/UserGroupForm.tsx
src/utils/FormRule.ts

[chore]: Expand character limit for name field in forms

---

src/api/audit_plan/index.d.ts
src/api/audit_plan/index.ts
src/api/common.d.ts
src/api/common.enum.ts
src/api/configuration/index.d.ts
src/api/configuration/index.ts
src/api/sql_audit/index.d.ts
src/api/sql_audit/index.ts
src/api/workflow/index.d.ts
src/page/Order/List/OrderListFilterForm/index.test.tsx
src/page/Order/List/OrderListFilterForm/index.tsx
src/page/Order/List/__snapshots__/index.test.tsx.snap
src/page/Order/List/index.test.tsx
src/page/Order/List/index.tsx

[chore]: Add filtering for description column in table

---

CHANGELOG.md
craco.config.js
src/api/audit_plan/index.d.ts
src/api/audit_plan/index.ts
src/api/common.d.ts
src/api/common.enum.ts
src/api/configuration/index.d.ts
src/api/configuration/index.ts
src/api/sql_audit/index.d.ts
src/api/sql_audit/index.ts
src/api/workflow/index.d.ts
src/locale/zh-CN/auditPlan.ts
src/page/AuditPlan/PlanDetail/Detail/Report/__snapshots__/index.test.tsx.snap
src/page/AuditPlan/PlanDetail/Detail/Report/index.test.tsx
src/page/AuditPlan/PlanDetail/Detail/Report/index.tsx

[feature]: Support export audit report

---

src/api/common.d.ts
src/api/rule_template/index.d.ts
src/api/rule_template/index.ts
src/api/sql_audit_record/index.d.ts
src/page/SQLManagement/SQLPanel/column.tsx
src/page/SqlAuditRecord/List/index.data.ts
src/page/SqlAuditRecord/List/index.tsx
src/page/SqlAuditRecord/List/index.type.ts

https://github.com/actiontech/sqle-ee/issues/1013

[feature]: Enable jumping to SQL review record list from SQL management module

---

src/page/Order/AuditResult/AuditResultInfo/index.tsx
src/page/Order/AuditResult/AuditResultInfo/index.type.ts
src/page/Order/AuditResult/column.tsx

[fix]: Add audit status check for render audit result info

---

src/api/SqlManage/index.d.ts
src/api/SqlManage/index.ts
src/api/common.d.ts
src/api/common.enum.ts
src/api/sql_audit/index.d.ts
src/api/sql_audit/index.ts
src/locale/zh-CN/sqlManagement.ts
src/page/SQLManagement/SQLPanel/FilterForm.tsx
src/page/SQLManagement/SQLPanel/hooks/useRuleTips.tsx
src/page/SQLManagement/SQLPanel/index.tsx
src/page/SQLManagement/SQLPanel/index.type.ts
src/utils/Common.ts

https://github.com/actiontech/sqle-ee/issues/1149

[feature]: (SQLManagement) Support list filtering based on rules

---

src/App.test.tsx
src/api/SqlManage/index.d.ts
src/api/SqlManage/index.ts
src/api/common.d.ts
src/api/common.enum.ts
src/api/companyNotice/index.d.ts
src/api/companyNotice/index.ts
src/api/sql_audit/index.d.ts
src/api/sql_audit/index.ts
src/components/Nav/Header/Component/CompanyNoticeTrigger.tsx
src/components/Nav/Header/Modal/CompanyNoticeModal/index.tsx
src/components/Nav/Header/Modal/__snapshots__/index.test.tsx.snap
src/components/Nav/Header/Modal/index.test.tsx
src/components/Nav/Header/Modal/index.tsx
src/components/Nav/Header/__snapshots__/index.test.tsx.snap
src/components/Nav/Header/index.tsx
src/components/Nav/__snapshots__/index.test.tsx.snap
src/components/Nav/index.less
src/data/ModalName.ts
src/data/StorageKey.ts
src/data/common.ts
src/locale/zh-CN/system.ts
src/page/Login/index.tsx

https://github.com/actiontech/sqle-ee/issues/1122

[feature]: Support publish company notice

---

src/api/SqlManage/index.d.ts
src/api/SqlManage/index.enum.ts
src/hooks/useTable/index.ts
src/page/SQLManagement/SQLPanel/column.tsx
src/page/SQLManagement/SQLPanel/index.tsx

https://github.com/actiontech/sqle-ee/issues/1166

[feature]:(SQLManagement) Support for list sorting

---

src/api/SqlManage/index.d.ts
src/api/SqlManage/index.enum.ts
src/api/task/index.d.ts
src/api/task/index.ts
src/locale/zh-CN/order.ts
src/page/Order/Create/SqlInfoForm/__test__/__snapshots__/index.test.tsx.snap
src/page/Order/Create/SqlInfoForm/__test__/index.test.tsx
src/page/Order/Create/__snapshots__/index.test.tsx.snap
src/page/Order/Detail/Modal/ModifySqlModal/__snapshots__/index.test.tsx.snap
src/page/Order/SqlStatementFormTabs/SqlStatementForm.tsx
src/page/Order/SqlStatementFormTabs/__test__/SqlStatementForm.test.tsx
src/page/Order/SqlStatementFormTabs/__test__/__snapshots__/SqlStatementForm.test.tsx.snap
src/page/Order/SqlStatementFormTabs/__test__/__snapshots__/SqlStatementFormTabs.test.tsx.snap
src/page/Order/SqlStatementFormTabs/index.ts
src/page/Order/hooks/useAuditOrder.tsx

fix: https://github.com/actiontech/sqle/issues/1969

[feature]: (Order) Support uploading sql zip files

---

src/page/SqlAuditRecord/Create/index.tsx

fix: [actiontech/sqle/issues/1973](https://github.com/actiontech/sqle/issues/1973)

[fix]: update sql audit create result show methods

---

src/hooks/useTable/index.test.ts
src/hooks/useTable/index.ts
src/page/AuditPlan/PlanDetail/Detail/Report/index.tsx
src/page/AuditPlan/PlanList/index.tsx
src/page/DataSource/DataSourceList/index.tsx
src/page/Member/MemberGroupList/index.tsx
src/page/Member/MemberList/index.tsx
src/page/OperationRecord/OperationRecordList/List.tsx
src/page/Order/AuditResult/index.tsx
src/page/Order/List/index.tsx
src/page/SQLManagement/SQLPanel/index.tsx
src/page/SqlAuditRecord/List/index.tsx
src/page/UserCenter/UserGroup/UserGroupList/index.tsx

issue: [2074](https://github.com/actiontech/sqle/issues/2074)
jira: [DMS-654](http://10.186.18.11/jira/browse/DMS-654)

[fix](has filter info list): table filter data change

---

src/hooks/useTable/index.test.ts
src/hooks/useTable/index.ts
src/page/AuditPlan/PlanList/index.tsx
src/page/DataSource/DataSourceList/index.tsx
src/page/Member/MemberGroupList/index.tsx
src/page/Member/MemberList/index.tsx
src/page/OperationRecord/OperationRecordList/List.tsx
src/page/Order/List/index.tsx
src/page/SQLManagement/SQLPanel/index.tsx
src/page/SQLManagement/index.tsx
src/page/SqlAuditRecord/List/index.tsx
src/page/UserCenter/UserGroup/UserGroupList/index.tsx

issue: https://github.com/actiontech/sqle/issues/2074
jira: [DMS-654](http://10.186.18.11/jira/browse/DMS-654)

[fix](use table hooks): controlled page size for use table

---

src/locale/en-US/order.ts
src/locale/zh-CN/order.ts
src/page/Order/SqlStatementFormTabs/SqlStatementForm.tsx
src/page/SqlAuditRecord/Create/SQLInfoForm.tsx
src/utils/FormRule.ts

[issue-2067](https://github.com/actiontech/sqle/issues/2067)

[fix]: update and unify sqlFile validate locale

---

src/page/Order/AuditResult/AuditResultInfo/index.tsx
src/page/Order/AuditResult/__test__/__snapshots__/AuditResultCollection.test.tsx.snap
src/page/Order/AuditResult/__test__/__snapshots__/AuditResultInfo.test.tsx.snap
src/page/Order/AuditResult/__test__/__snapshots__/index.test.tsx.snap
src/page/Order/Create/__snapshots__/index.test.tsx.snap
src/page/Order/Detail/__snapshots__/index.test.tsx.snap

closes to [issue-2090](https://github.com/actiontech/sqle/issues/2090)

[fix](AuditResultInfo): fix passed result box style

---

src/locale/en-US/common.ts
src/locale/en-US/order.ts
src/locale/zh-CN/common.ts
src/locale/zh-CN/order.ts
src/page/Order/SqlStatementFormTabs/SqlStatementForm.tsx
src/page/SqlAuditRecord/Create/SQLInfoForm.tsx

closes to [issue-2067](https://github.com/actiontech/sqle/issues/2067)

[fix]: change file valid locale

---

src/api/SqlManage/index.d.ts
src/api/SqlManage/index.ts
src/api/audit_plan/index.d.ts
src/api/audit_plan/index.ts
src/api/common.d.ts
src/page/SQLManagement/SQLPanel/FilterForm.tsx
src/page/SQLManagement/SQLPanel/column.tsx
src/page/SQLManagement/SQLPanel/index.tsx
src/page/SQLManagement/SQLPanel/index.type.ts

[actiontech/sqle#1271](https://github.com/actiontech/sqle-ee/issues/1271)

[feature]:(SQLManagement) build api and add schema column for list

---

src/api/SqlManage/index.d.ts
src/api/SqlManage/index.ts
src/api/common.d.ts
src/locale/zh-CN/sqlManagement.ts
src/page/SQLManagement/SQLPanel/column.tsx
src/page/SQLManagement/SQLPanel/index.tsx
src/page/SqlAnalyze/SqlManage/index.tsx
src/page/SqlAnalyze/SqlManage/index.type.ts
src/router/config.tsx
src/types/router.type.ts

https://github.com/actiontech/sqle-ee/issues/1266

[feature]:(SQLManagement) Support sql analyze

---

src/api/SqlManage/index.d.ts
src/api/common.d.ts
src/locale/zh-CN/sqlManagement.ts
src/page/SQLManagement/SQLPanel/FilterForm.tsx
src/page/SQLManagement/SQLPanel/column.tsx
src/page/SQLManagement/SQLPanel/index.less
src/page/SQLManagement/SQLPanel/index.tsx
src/page/SQLManagement/SQLPanel/index.type.ts

issue: https://github.com/actiontech/sqle-ee/issues/1362

[feature](SQLManagement): Add scan name filter item and display format
